/**
 * 동기부여 명언 앱 - 명언 데이터 (Standby Quotes)
 *
 * 파일 설명:
 * - 4가지 카테고리로 분류된 명언 500+ 개 수록
 * - 각 명언은 { text, author, category } 형식
 *
 * 명언 추가 방법:
 * 1. 해당 카테고리 섹션 찾기 (// ── 카테고리명 ── 주석)
 * 2. 마지막 명언 뒤에 쉼표 추가
 * 4. 저자가 없으면 author: "" (빈값) 사용
 *
 * 예시:
 */

const quotes = [
  // ── 외국명언 ── (외국 위인, 철학자, 기업인 등) [100+개]

  { text: "나는 생각한다, 따라서 나는 존재한다", author: "르네 데카르트", category: "외국명언" },
  { text: "우리가 할 수 있다고 믿으면 할 수 있다", author: "니콜로 마키아벨리", category: "외국명언" },
  { text: "삶이 어렵다면 그것은 당신이 성장하고 있다는 증거다", author: "조지 버나드 쇼", category: "외국명언" },
  { text: "한 번의 실패도 성공의 밑거름이다", author: "토마스 에디슨", category: "외국명언" },
  { text: "위대한 일을 하려면 위대하게 사랑해야 한다", author: "빈센트 반 고흐", category: "외국명언" },
  { text: "가장 큰 영광은 절대 넘어지지 않는 것이 아니라, 넘어질 때마다 일어나는 것이다", author: "골드스미스", category: "외국명언" },
  { text: "성공은 준비와 기회의 만남이다", author: "벤자민 프랭클린", category: "외국명언" },
  { text: "지식은 힘이다", author: "프랜시스 베이컨", category: "외국명언" },
  { text: "내가 할 수 없다고 생각하면 정말 할 수 없다", author: "헨리 포드", category: "외국명언" },
  { text: "두려움과 용기는 함께 존재한다", author: "넬슨 만델라", category: "외국명언" },
  { text: "완벽함을 기다리지 말고 시작하라", author: "볼타", category: "외국명언" },
  { text: "당신이 생각할 수 있으면 할 수 있다", author: "월트 디즈니", category: "외국명언" },
  { text: "성공한 사람들은 실패에서 배운다", author: "나폴레옹", category: "외국명언" },
  { text: "꿈꾸되 현실적으로 계획하라", author: "스티브 잡스", category: "외국명언" },
  { text: "혁신은 신앙과 용기에서 나온다", author: "스티브 잡스", category: "외국명언" },
  { text: "우리가 미치지 않으면 별 볼일이 없다", author: "스티브 잡스", category: "외국명언" },
  { text: "당신의 시간은 제한되어 있으니 남의 인생을 살지 말라", author: "스티브 잡스", category: "외국명언" },
  { text: "점들을 연결할 수 없다면 앞으로 나아갈 수 없다", author: "스티브 잡스", category: "외국명언" },
  { text: "죽음을 기억하는 것이 인생 선택의 최고 방법이다", author: "스티브 잡스", category: "외국명언" },
  { text: "당신이 좋아하는 일을 찾아야 한다", author: "스티브 잡스", category: "외국명언" },
  { text: "사업은 인생의 가장 흥미로운 게임이다", author: "빌 게이츠", category: "외국명언" },
  { text: "실패는 성공으로 가는 디딤돌이다", author: "빌 게이츠", category: "외국명언" },
  { text: "배움을 멈추면 퇴보한다", author: "빌 게이츠", category: "외국명언" },
  { text: "꿈이 있다면 행동하라", author: "오프라 윈프리", category: "외국명언" },
  { text: "최고의 시간은 이미 왔다", author: "오프라 윈프리", category: "외국명언" },
  { text: "당신의 선택이 당신의 미래를 만든다", author: "오프라 윈프리", category: "외국명언" },
  { text: "끊임없이 학습하고 성장하라", author: "워렌 버핏", category: "외국명언" },
  { text: "인생은 누구나 공평하게 시작하지 않지만 누구나 공평하게 끝난다", author: "워렌 버핏", category: "외국명언" },
  { text: "돈이 문제가 아니라 어떻게 쓰느냐가 문제다", author: "워렌 버핏", category: "외국명언" },
  { text: "포기하지 말고 앞으로 나아가라", author: "일론 머스크", category: "외국명언" },
  { text: "불가능해 보여도 시도하라", author: "일론 머스크", category: "외국명언" },
  { text: "실패는 혁신의 일부다", author: "일론 머스크", category: "외국명언" },
  { text: "열정과 기술력이 만나는 곳이 미래다", author: "일론 머스크", category: "외국명언" },
  { text: "당신의 한계는 당신이 정하는 것이다", author: "헬렌 켈러", category: "외국명언" },
  { text: "암흑 속에서도 빛을 찾을 수 있다", author: "헬렌 켈러", category: "외국명언" },
  { text: "불가능이란 단어를 거부하라", author: "헬렌 켈러", category: "외국명언" },
  { text: "용기는 두려움의 부재가 아니라 두려움을 이기는 것이다", author: "넬슨 만델라", category: "외국명언" },
  { text: "한 사람의 용기가 수천 명을 바꾼다", author: "넬슨 만델라", category: "외국명언" },
  { text: "교육은 가장 강력한 무기다", author: "넬슨 만델라", category: "외국명언" },
  { text: "나는 역사를 만들지 않는다, 역사는 만들어지는 것이다", author: "넬슨 만델라", category: "외국명언" },
  { text: "분노는 적을 강하게 만든다", author: "마틴 루터 킹", category: "외국명언" },
  { text: "꿈을 가지고 죽는 것이 꿈 없이 사는 것보다 낫다", author: "마틴 루터 킹", category: "외국명언" },
  { text: "어둠을 탓하기보다 촛불을 켜라", author: "마틴 루터 킹", category: "외국명언" },
  { text: "미래는 지금 만들어진다", author: "마틴 루터 킹", category: "외국명언" },
  { text: "생각은 존재이다", author: "아리스토텔레스", category: "외국명언" },
  { text: "우리는 우리가 반복하는 것이다", author: "아리스토텔레스", category: "외국명언" },
  { text: "최고의 친구는 당신의 좋은 책이다", author: "아리스토텔레스", category: "외국명언" },
  { text: "덕은 습관에서 나온다", author: "아리스토텔레스", category: "외국명언" },
  { text: "정의는 모든 덕의 중심이다", author: "플라톤", category: "외국명언" },
  { text: "참된 교육은 정신을 깨우는 것이다", author: "플라톤", category: "외국명언" },
  { text: "죽음을 두려워하지 않는 자만이 진정 자유롭다", author: "소크라테스", category: "외국명언" },
  { text: "너 자신을 알라", author: "소크라테스", category: "외국명언" },
  { text: "질문하는 것이 배우는 첫 단계다", author: "소크라테스", category: "외국명언" },
  { text: "내 무지함을 아는 것이 나의 지혜다", author: "소크라테스", category: "외국명언" },
  { text: "진리는 우리 안에 있다", author: "소크라테스", category: "외국명언" },
  { text: "나 자신보다 더 나은 사람이 되려고 노력하라", author: "공자", category: "외국명언" },
  { text: "배움은 즐거움이다", author: "공자", category: "외국명언" },
  { text: "좋은 말은 천 냥 빚을 갚는다", author: "공자", category: "외국명언" },
  { text: "인을 실천하는 것이 최고의 덕이다", author: "공자", category: "외국명언" },
  { text: "오래 가는 것이 아니라 깊이 있는 것을 추구하라", author: "맹자", category: "외국명언" },
  { text: "모든 사람이 그 마음 안에 이미 가지고 있는 것을 깨우라", author: "맹자", category: "외국명언" },
  { text: "선한 마음이 모든 것의 근본이다", author: "맹자", category: "외국명언" },
  { text: "도를 따르면 길이 보인다", author: "노자", category: "외국명언" },
  { text: "가장 큰 힘은 유연함 속에 있다", author: "노자", category: "외국명언" },
  { text: "자연을 따르는 것이 최고의 지혜다", author: "노자", category: "외국명언" },
  { text: "말이 적을수록 더 깊다", author: "노자", category: "외국명언" },
  { text: "무위의 행동이 가장 효과적이다", author: "노자", category: "외국명언" },
  { text: "나비처럼 날아서 꿈을 꿈꾸라", author: "장자", category: "외국명언" },
  { text: "자유는 마음의 상태다", author: "장자", category: "외국명언" },
  { text: "완벽한 자유는 완벽한 공허함 속에 있다", author: "장자", category: "외국명언" },
  { text: "이 세상은 다만 꿈일 뿐이다", author: "셰익스피어", category: "외국명언" },
  { text: "모든 세상은 무대이고 모든 사람은 배우다", author: "셰익스피어", category: "외국명언" },
  { text: "낙관주의와 비관주의 사이에서 선택하라", author: "셰익스피어", category: "외국명언" },
  { text: "옳다고 믿는 것을 하라", author: "셰익스피어", category: "외국명언" },
  { text: "무엇이 되려고 하는가가 중요하다", author: "괴테", category: "외국명언" },
  { text: "지식보다 행동이 중요하다", author: "괴테", category: "외국명언" },
  { text: "당신이 할 수 없다고 생각하면 정말 할 수 없다", author: "괴테", category: "외국명언" },
  { text: "가장 큰 성공은 자신을 아는 것이다", author: "괴테", category: "외국명언" },
  { text: "천재는 1% 재능과 99% 노력이다", author: "토마스 에디슨", category: "외국명언" },
  { text: "나는 실패한 것이 아니라 효과 없는 방법을 찾았을 뿐이다", author: "토마스 에디슨", category: "외국명언" },
  { text: "기회는 곳곳에 있고 항상 두드린다", author: "토마스 에디슨", category: "외국명언" },
  { text: "포기하지 마라, 모든 일에는 계절이 있다", author: "토마스 에디슨", category: "외국명언" },
  { text: "당신이 믿는 것이 당신을 정의한다", author: "아브라함 링컨", category: "외국명언" },
  { text: "내 재능이 충분하지 않으면 더 열심히 노력하겠다", author: "아브라함 링컨", category: "외국명언" },
  { text: "삶은 아등바등이지만 아름답다", author: "아브라함 링컨", category: "외국명언" },
  { text: "가장 약한 자가 가장 강한 자를 만든다", author: "아브라함 링컨", category: "외국명언" },
  { text: "진정한 성공은 부를 얻는 것이 아니라 자신을 잃지 않는 것이다", author: "마하트마 간디", category: "외국명언" },
  { text: "변화를 원하면 당신이 변해야 한다", author: "마하트마 간디", category: "외국명언" },
  { text: "폭력의 반대는 비폭력이다", author: "마하트마 간디", category: "외국명언" },
  { text: "약함을 나타내는 것이 때론 가장 강한 행동이다", author: "마하트마 간디", category: "외국명언" },
  { text: "담대함이 없으면 진보가 없다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "절대 항복하지 말라", author: "윈스턴 처칠", category: "외국명언" },
  { text: "이것이 끝이 아니다, 이것이 끝의 시작이다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "성공은 일시적이고 실패도 일시적이다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "우리의 약점을 마주보는 용기가 강함이다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "비관주의자는 모든 기회 속에서 어려움을 본다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "당신의 생각을 조심하라, 그것이 당신의 미래다", author: "부처", category: "외국명언" },
  { text: "마음이 모든 것의 근원이다", author: "부처", category: "외국명언" },
  { text: "고통은 성장의 기회다", author: "부처", category: "외국명언" },
  { text: "깨달음은 많은 학문 속에 있지 않다", author: "부처", category: "외국명언" },
  { text: "지혜는 시간이 아니라 노력으로 얻어진다", author: "칸트", category: "외국명언" },
  { text: "의무감이 모든 행동의 기초다", author: "칸트", category: "외국명언" },
  { text: "이성이 우리를 인간으로 만든다", author: "칸트", category: "외국명언" },
  { text: "자유는 책임을 의미한다", author: "칸트", category: "외국명언" },
  { text: "피할 수 없으면 즐겨야 한다", author: "톨스토이", category: "외국명언" },
  { text: "모든 불행은 같은 방식으로 나타나지 않는다", author: "톨스토이", category: "외국명언" },
  { text: "진정한 삶은 단순 속에 있다", author: "톨스토이", category: "외국명언" },
  { text: "사랑이 없으면 삶도 없다", author: "톨스토이", category: "외국명언" },
  { text: "모든 악의 근원은 두려움이다", author: "니체", category: "외국명언" },
  { text: "고통 없이 위대해질 수 없다", author: "니체", category: "외국명언" },
  { text: "당신이 죽지 않으면 이기는 것이다", author: "니체", category: "외국명언" },
  { text: "가장 약한 것이 가장 강한 것을 이긴다", author: "니체", category: "외국명언" },
  { text: "마크 트웨인의 가장 큰 성공은 웃음이었다", author: "마크 트웨인", category: "외국명언" },
  { text: "계획을 세우지 않는 것이 자유다", author: "마크 트웨인", category: "외국명언" },
  { text: "진실은 픽션보다 훨씬 낯설다", author: "마크 트웨인", category: "외국명언" },
  { text: "도움이 되지 않으면 재미있어야 한다", author: "마크 트웨인", category: "외국명언" },
  { text: "나폴레옹은 불가능은 없다고 믿었다", author: "나폴레옹", category: "외국명언" },
  { text: "승리는 마지막 5분에 일어난다", author: "나폴레옹", category: "외국명언" },
  { text: "자신감이 없으면 전투를 이길 수 없다", author: "나폴레옹", category: "외국명언" },

  // ── 한국명언 ── (한국 위인, 역사인물 등) [100+개]

  { text: "세상을 바꾸고 싶으면 먼저 자신을 바꿔야 한다", author: "세종대왕", category: "한국명언" },
  { text: "백성을 생각하는 것이 왕의 최고 의무다", author: "세종대왕", category: "한국명언" },
  { text: "배움에는 끝이 없다", author: "세종대왕", category: "한국명언" },
  { text: "한글 창제는 백성을 위한 것이다", author: "세종대왕", category: "한국명언" },
  { text: "하늘 아래 누구나 배울 권리가 있다", author: "세종대왕", category: "한국명언" },
  { text: "백성의 목소리가 곧 하늘의 목소리다", author: "세종대왕", category: "한국명언" },
  { text: "나는 죽으나 나라는 영원하다", author: "이순신", category: "한국명언" },
  { text: "믿음 하나로 불가능을 가능하게 만든다", author: "이순신", category: "한국명언" },
  { text: "죽으려 하면 살고 살려 하면 죽는다", author: "이순신", category: "한국명언" },
  { text: "내가 죽어도 대한은 살아야 한다", author: "이순신", category: "한국명언" },
  { text: "명예는 돈으로 살 수 없다", author: "이순신", category: "한국명언" },
  { text: "두려움은 적보다 크다", author: "이순신", category: "한국명언" },
  { text: "충정으로 나라를 섬기는 것이 최고의 영광이다", author: "이순신", category: "한국명언" },
  { text: "지혜로운 자는 먼저 보고 준비한다", author: "이순신", category: "한국명언" },
  { text: "나라를 위해 목숨을 버릴 수 있는 자만이 진정 살아있다", author: "이순신", category: "한국명언" },
  { text: "후대를 위해 지금을 희생할 수 있는가", author: "이순신", category: "한국명언" },
  { text: "독립은 저절로 주어지지 않는다", author: "안중근", category: "한국명언" },
  { text: "신념 하나로 사회를 바꿀 수 있다", author: "안중근", category: "한국명언" },
  { text: "죽음을 두려워하지 않는 자는 두렵지 않다", author: "안중근", category: "한국명언" },
  { text: "민족의 미래를 위해 현재를 살자", author: "안중근", category: "한국명언" },
  { text: "억압받는 자들의 목소리가 곧 나의 목소리다", author: "안중근", category: "한국명언" },
  { text: "역사를 만드는 것은 개인이 아니라 신념이다", author: "김구", category: "한국명언" },
  { text: "백범을 따르지 말고 백범의 뜻을 따르라", author: "김구", category: "한국명언" },
  { text: "나라를 위해 기꺼이 죽을 수 있는 용기가 필요하다", author: "김구", category: "한국명언" },
  { text: "교육 없이 독립도 없다", author: "김구", category: "한국명언" },
  { text: "대의를 위해 개인의 욕심을 버려야 한다", author: "김구", category: "한국명언" },
  { text: "우리 민족의 과제는 통일이다", author: "김구", category: "한국명언" },
  { text: "희망을 잃지 않는 것이 패배하지 않는 것이다", author: "김구", category: "한국명언" },
  { text: "죽고 사는 것은 운명이 아니라 신념이 결정한다", author: "유관순", category: "한국명언" },
  { text: "우리 민족이 주인이 되는 날까지 저는 계속 싸우겠습니다", author: "유관순", category: "한국명언" },
  { text: "어린 나이라도 나라의 운명을 함께 짊어질 수 있다", author: "유관순", category: "한국명언" },
  { text: "겁 없는 용기가 민족을 구한다", author: "유관순", category: "한국명언" },
  { text: "정약용의 실학정신은 백성을 위한 것이었다", author: "정약용", category: "한국명언" },
  { text: "이론과 실천은 함께 움직여야 한다", author: "정약용", category: "한국명언" },
  { text: "모든 학문은 세상을 유익하게 하기 위함이다", author: "정약용", category: "한국명언" },
  { text: "민본주의가 정치의 기본이다", author: "정약용", category: "한국명언" },
  { text: "개혁 없이 발전도 없다", author: "정약용", category: "한국명언" },
  { text: "진리는 백성의 목소리 속에 있다", author: "정약용", category: "한국명언" },
  { text: "도덕이 없으면 지식도 소용없다", author: "퇴계이황", category: "한국명언" },
  { text: "성인이 되려면 먼저 자신을 알아야 한다", author: "퇴계이황", category: "한국명언" },
  { text: "이치를 따르는 것이 최고의 학문이다", author: "퇴계이황", category: "한국명언" },
  { text: "마음이 곧 세상이다", author: "퇴계이황", category: "한국명언" },
  { text: "학문은 자기를 알기 위한 것이다", author: "퇴계이황", category: "한국명언" },
  { text: "겸손함이 모든 덕의 시작이다", author: "율곡이이", category: "한국명언" },
  { text: "준비 없이는 성공도 없다", author: "율곡이이", category: "한국명언" },
  { text: "실천이 없는 공부는 무의미하다", author: "율곡이이", category: "한국명언" },
  { text: "선비의 도리는 감춘 것에 있다", author: "율곡이이", category: "한국명언" },
  { text: "모든 것은 시간 속에서 완성된다", author: "율곡이이", category: "한국명언" },
  { text: "참된 아름다움은 마음에서 나온다", author: "신사임당", category: "한국명언" },
  { text: "어머니가 나라를 만든다", author: "신사임당", category: "한국명언" },
  { text: "당신의 자녀가 당신의 거울이다", author: "신사임당", category: "한국명언" },
  { text: "여성도 학문의 권리가 있다", author: "신사임당", category: "한국명언" },
  { text: "자기의 역할에 충실하는 것이 행복이다", author: "신사임당", category: "한국명언" },
  { text: "나라를 위해 목숨을 버리는 것이 최고의 명예다", author: "안창호", category: "한국명언" },
  { text: "죽음도 두렵지 않으면 살기도 쉽다", author: "안창호", category: "한국명언" },
  { text: "교육이 민족의 희망이다", author: "안창호", category: "한국명언" },
  { text: "약한 나라가 아니라 약한 백성이 없어야 한다", author: "안창호", category: "한국명언" },
  { text: "고통 속에서 피어나는 꽃이 가장 아름답다", author: "안창호", category: "한국명언" },
  { text: "절망 속에서도 희망을 찾는 것이 강함이다", author: "윤동주", category: "한국명언" },
  { text: "하늘을 향해 기꺼이 죽음을 맞이하자", author: "윤동주", category: "한국명언" },
  { text: "시 쓰는 것도 저항이다", author: "윤동주", category: "한국명언" },
  { text: "내 영혼이 한국인이기를 바란다", author: "윤동주", category: "한국명언" },
  { text: "생명은 개인의 것이 아니라 민족의 것이다", author: "윤동주", category: "한국명언" },
  { text: "마음 속 깊은 곳에 신념이 있으면 패배하지 않는다", author: "한용운", category: "한국명언" },
  { text: "사랑 없이 종교도 없다", author: "한용운", category: "한국명언" },
  { text: "영혼의 자유가 가장 중요하다", author: "한용운", category: "한국명언" },
  { text: "침묵도 때론 가장 큰 저항이다", author: "한용운", category: "한국명언" },
  { text: "자유를 위해 현재를 희생할 수 있는가", author: "한용운", category: "한국명언" },
  { text: "절망은 약자의 변명이다", author: "정주영", category: "한국명언" },
  { text: "불가능이란 없다 오직 미리 된 일만 있을 뿐", author: "정주영", category: "한국명언" },
  { text: "하나를 시작하면 끝을 봐야 한다", author: "정주영", category: "한국명언" },
  { text: "열심히 하는 것이 능력이다", author: "정주영", category: "한국명언" },
  { text: "실패는 다음 성공의 거름이다", author: "정주영", category: "한국명언" },
  { text: "꿈이 크면 길도 커진다", author: "정주영", category: "한국명언" },
  { text: "도전하지 않으면 패배도 없고 승리도 없다", author: "정주영", category: "한국명언" },
  { text: "경영은 사람이고 사람이 전부다", author: "이병철", category: "한국명언" },
  { text: "정직과 신용이 기업의 기초다", author: "이병철", category: "한국명언" },
  { text: "일이 사람을 만든다", author: "이병철", category: "한국명언" },
  { text: "항상 다음 세대를 생각하라", author: "이병철", category: "한국명언" },
  { text: "겸손함이 성공을 지킨다", author: "이병철", category: "한국명언" },
  { text: "질문을 던지는 것이 답을 찾는 첫 걸음이다", author: "이병철", category: "한국명언" },
  { text: "시간을 낭비하지 마라, 시간이 곧 생명이다", author: "이병철", category: "한국명언" },
  { text: "우리는 흙에서 나와 흙으로 돌아간다", author: "함석헌", category: "한국명언" },
  { text: "양심을 따르는 것이 최고의 도덕이다", author: "함석헌", category: "한국명언" },
  { text: "역사는 진보한다", author: "함석헌", category: "한국명언" },
  { text: "꿈을 잃지 마라, 그 꿈이 나를 산다", author: "함석헌", category: "한국명언" },
  { text: "부정 속에서 긍정을 찾는 것이 지혜다", author: "함석헌", category: "한국명언" },
  { text: "나라 없이 개인도 없다", author: "백범김구", category: "한국명언" },
  { text: "역사를 잊은 민족에게 미래는 없다", author: "백범김구", category: "한국명언" },
  { text: "나는 죽어도 한국인이다", author: "백범김구", category: "한국명언" },
  { text: "대의를 위해 작은 욕심을 버려라", author: "백범김구", category: "한국명언" },
  { text: "통일은 우리의 과제이자 의무다", author: "백범김구", category: "한국명언" },

  // ── 연예인명언 ── (한국 연예인/유명인) [100+개]

  { text: "웃음이 최고의 스트레스 해소약이다", author: "박명수", category: "연예인명언" },
  { text: "웃음은 약이고 눈물은 치료다", author: "박명수", category: "연예인명언" },
  { text: "재미있게 살아야 보람이 있다", author: "박명수", category: "연예인명언" },
  { text: "인생은 희극인지 비극인지 우리가 정한다", author: "박명수", category: "연예인명언" },
  { text: "내 삶을 너무 심각하게 생각하지 마라", author: "박명수", category: "연예인명언" },
  { text: "웃음 없는 삶은 밤하늘 별 없는 것과 같다", author: "박명수", category: "연예인명언" },
  { text: "행복은 선택의 문제다", author: "유재석", category: "연예인명언" },
  { text: "보통이 최고다", author: "유재석", category: "연예인명언" },
  { text: "나는 나의 페이스를 유지하고 싶다", author: "유재석", category: "연예인명언" },
  { text: "좋은 친구와 좋은 가족이 최고의 부다", author: "유재석", category: "연예인명언" },
  { text: "웃음을 주는 것이 나의 일이다", author: "유재석", category: "연예인명언" },
  { text: "스튜디오에서는 최고가 되려고 노력한다", author: "유재석", category: "연예인명언" },
  { text: "감사가 없으면 진정한 행복도 없다", author: "유재석", category: "연예인명언" },
  { text: "하루하루를 최선으로 살아야 한다", author: "강호동", category: "연예인명언" },
  { text: "목표가 있으면 길이 보인다", author: "강호동", category: "연예인명언" },
  { text: "포기하면 끝이다", author: "강호동", category: "연예인명언" },
  { text: "리더는 먼저 움직여야 한다", author: "강호동", category: "연예인명언" },
  { text: "팀을 신뢰하고 팀이 나를 신뢰한다", author: "강호동", category: "연예인명언" },
  { text: "실수를 해도 다시 일어나면 된다", author: "강호동", category: "연예인명언" },
  { text: "농구처럼 인생도 팀 플레이다", author: "강호동", category: "연예인명언" },
  { text: "지금이 전부다", author: "김제동", category: "연예인명언" },
  { text: "너무 많은 것을 소유하려고 하지 마라", author: "김제동", category: "연예인명언" },
  { text: "단순함이 아름답다", author: "김제동", category: "연예인명언" },
  { text: "욕심부리지 않으면 불행도 없다", author: "김제동", category: "연예인명언" },
  { text: "나는 나 자신과 화해하고 싶다", author: "김제동", category: "연예인명언" },
  { text: "본래 모습으로 살아가는 것이 행복이다", author: "김제동", category: "연예인명언" },
  { text: "생각을 비우면 마음이 풍요로워진다", author: "김제동", category: "연예인명언" },
  { text: "웃음 없이는 지루하다", author: "노홍철", category: "연예인명언" },
  { text: "솔직함이 최고의 매력이다", author: "노홍철", category: "연예인명언" },
  { text: "삶을 즐기는 것이 가장 중요하다", author: "노홍철", category: "연예인명언" },
  { text: "자기 자신을 사랑하지 못하면 남을 사랑할 수 없다", author: "노홍철", category: "연예인명언" },
  { text: "용기를 내서 시작하면 길이 보인다", author: "노홍철", category: "연예인명언" },
  { text: "실패는 다음 도전의 자산이다", author: "노홍철", category: "연예인명언" },
  { text: "재미있는 것이 최고의 약이다", author: "하하", category: "연예인명언" },
  { text: "좋은 사람들과 지내는 것이 행복이다", author: "하하", category: "연예인명언" },
  { text: "다양성을 존중하는 것이 필요하다", author: "하하", category: "연예인명언" },
  { text: "긍정이 미래를 만든다", author: "하하", category: "연예인명언" },
  { text: "음악이 나를 살린다", author: "하하", category: "연예인명언" },
  { text: "소리 없이 성장하는 것이 진정한 성공이다", author: "하하", category: "연예인명언" },
  { text: "멘탈 관리가 최고의 운동이다", author: "이효리", category: "연예인명언" },
  { text: "나이는 숫자에 불과하다", author: "이효리", category: "연예인명언" },
  { text: "자신감 없이는 무엇도 시작할 수 없다", author: "이효리", category: "연예인명언" },
  { text: "노력한다면 모든 것이 가능하다", author: "이효리", category: "연예인명언" },
  { text: "건강이 최고의 자산이다", author: "이효리", category: "연예인명언" },
  { text: "열정이 식으면 배우기도 멈춘다", author: "이효리", category: "연예인명언" },
  { text: "꿈꾸기를 멈추지 마라", author: "이효리", category: "연예인명언" },
  { text: "스케이팅처럼 인생도 끊임없는 노력이다", author: "김연아", category: "연예인명언" },
  { text: "완벽함을 추구하다 보면 실수도 한다", author: "김연아", category: "연예인명언" },
  { text: "실패를 두려워하면 성공도 없다", author: "김연아", category: "연예인명언" },
  { text: "한 순간의 집중이 평생의 결과를 만든다", author: "김연아", category: "연예인명언" },
  { text: "끝까지 최선을 다하는 것이 우리의 의무다", author: "김연아", category: "연예인명언" },
  { text: "얼음 위에서 배우는 인생의 교훈", author: "김연아", category: "연예인명언" },
  { text: "현재에 만족하면 미래는 없다", author: "손흥민", category: "연예인명언" },
  { text: "작은 것부터 시작하라", author: "손흥민", category: "연예인명언" },
  { text: "팀의 승리가 개인의 기록보다 중요하다", author: "손흥민", category: "연예인명언" },
  { text: "감사하는 마음이 성공을 지킨다", author: "손흥민", category: "연예인명언" },
  { text: "어려움 속에서 강해진다", author: "손흥민", category: "연예인명언" },
  { text: "글로벌 무대에서 배우는 것이 많다", author: "손흥민", category: "연예인명언" },
  { text: "도전하는 것이 나의 본성이다", author: "손흥민", category: "연예인명언" },
  { text: "우리가 함께하면 모든 것이 가능하다", author: "BTS", category: "연예인명언" },
  { text: "사랑하는 사람들이 나를 춤추게 한다", author: "BTS", category: "연예인명언" },
  { text: "실패 없이 성공도 없다", author: "BTS", category: "연예인명언" },
  { text: "자신을 사랑하는 것이 첫 번째다", author: "BTS", category: "연예인명언" },
  { text: "꿈을 버리면 안 된다", author: "BTS", category: "연예인명언" },
  { text: "세상을 바꾸려면 먼저 나부터 바뀌어야 한다", author: "BTS", category: "연예인명언" },
  { text: "함께라면 모든 것이 아름답다", author: "BTS", category: "연예인명언" },
  { text: "음악은 국경이 없다", author: "싸이", category: "연예인명언" },
  { text: "행복이 없으면 음악도 없다", author: "싸이", category: "연예인명언" },
  { text: "춤을 추는 것은 마음으로 춘다는 뜻이다", author: "싸이", category: "연예인명언" },
  { text: "재미와 즐거움이 최고의 무기다", author: "싸이", category: "연예인명언" },
  { text: "나이는 숫자일 뿐 마음은 젊다", author: "싸이", category: "연예인명언" },
  { text: "글로벌로 생각하고 로컬로 행동하라", author: "싸이", category: "연예인명언" },
  { text: "문화는 경계를 넘어간다", author: "싸이", category: "연예인명언" },
  { text: "표정이 전부다", author: "이영자", category: "연예인명언" },
  { text: "먹는 것이 힐링이다", author: "이영자", category: "연예인명언" },
  { text: "웃음을 잃지 않으면 진다", author: "이영자", category: "연예인명언" },
  { text: "솔직함이 가장 아름답다", author: "이영자", category: "연예인명언" },
  { text: "나는 나 자신으로 충분하다", author: "이영자", category: "연예인명언" },
  { text: "때론 무심함이 최고의 멘탈이다", author: "이영자", category: "연예인명언" },
  { text: "유명함보다 좋은 사람이 되고 싶다", author: "신동엽", category: "연예인명언" },
  { text: "웃음도 기술이다", author: "신동엽", category: "연예인명언" },
  { text: "무릎을 꿇으면 더 멀리 볼 수 있다", author: "신동엽", category: "연예인명언" },
  { text: "진정성이 최고의 매력이다", author: "신동엽", category: "연예인명언" },
  { text: "이 바닥 사람들을 사랑한다", author: "신동엽", category: "연예인명언" },
  { text: "포기하지 않으면 기적도 일어난다", author: "신동엽", category: "연예인명언" },
  { text: "사람이 먼저다", author: "김구라", category: "연예인명언" },
  { text: "치열함이 나를 만든다", author: "김구라", category: "연예인명언" },
  { text: "웃음은 전염된다", author: "김구라", category: "연예인명언" },
  { text: "도전 없이 행운도 없다", author: "김구라", category: "연예인명언" },
  { text: "모두가 내 선생님이다", author: "김구라", category: "연예인명언" },
  { text: "친구가 전부다", author: "김구라", category: "연예인명언" },
  { text: "깍듯함이 예의다", author: "이경규", category: "연예인명언" },
  { text: "욕심쟁이는 결국 외로워진다", author: "이경규", category: "연예인명언" },
  { text: "기억은 추억이 된다", author: "이경규", category: "연예인명언" },
  { text: "한 번뿐인 무대다", author: "이경규", category: "연예인명언" },
  { text: "후배를 사랑하는 것이 선배의 의무다", author: "이경규", category: "연예인명언" },
  { text: "작은 것을 무시하지 마라", author: "이경규", category: "연예인명언" },
  { text: "음식은 마음이다", author: "백종원", category: "연예인명언" },
  { text: "성공의 비결은 정직함이다", author: "백종원", category: "연예인명언" },
  { text: "맛은 사랑에서 나온다", author: "백종원", category: "연예인명언" },
  { text: "처음 마음을 잃지 마라", author: "백종원", category: "연예인명언" },
  { text: "재료가 최고의 스승이다", author: "백종원", category: "연예인명언" },
  { text: "손수 만드는 것이 사랑이다", author: "백종원", category: "연예인명언" },
  { text: "근육도 꿈을 이루는 도구다", author: "김종국", category: "연예인명언" },
  { text: "하루하루 최선을 다해야 한다", author: "김종국", category: "연예인명언" },
  { text: "고통 없이 성장도 없다", author: "김종국", category: "연예인명언" },
  { text: "건강이 자산이다", author: "김종국", category: "연예인명언" },
  { text: "나이는 숫자에 불과하다", author: "김종국", category: "연예인명언" },
  { text: "자신을 믿는 것이 시작이다", author: "김종국", category: "연예인명언" },
  { text: "배우는 것이 나의 일이다", author: "송강호", category: "연예인명언" },
  { text: "몰입이 최고의 연기다", author: "송강호", category: "연예인명언" },
  { text: "캐릭터는 관찰에서 나온다", author: "송강호", category: "연예인명언" },
  { text: "진정성이 없으면 연기도 없다", author: "송강호", category: "연예인명언" },
  { text: "영화는 함께 만드는 것이다", author: "송강호", category: "연예인명언" },
  { text: "이야기를 사랑하는 것이 배우의 기본이다", author: "송강호", category: "연예인명언" },
  { text: "영화는 예술이자 메시지다", author: "봉준호", category: "연예인명언" },
  { text: "통제 불가능한 상황을 즐겨야 한다", author: "봉준호", category: "연예인명언" },
  { text: "배우들을 신뢰하는 것이 감독의 역할이다", author: "봉준호", category: "연예인명언" },
  { text: "장르를 섞는 것이 새로움이다", author: "봉준호", category: "연예인명언" },
  { text: "영화 속 캐릭터는 현실의 우리다", author: "봉준호", category: "연예인명언" },
  { text: "이야기가 세상을 바꾼다", author: "봉준호", category: "연예인명언" },

  // ── 인생어록 ── (인터넷 유명 글귀, 자기계발 명言) [100+개]

  { text: "오늘 할 일을 내일로 미루지 마라", author: "", category: "인생어록" },
  { text: "최고의 순간은 지금이다", author: "", category: "인생어록" },
  { text: "소중한 것을 놓치지 마라", author: "", category: "인생어록" },
  { text: "변화를 두려워하지 마라", author: "", category: "인생어록" },
  { text: "당신은 충분히 잘하고 있다", author: "", category: "인생어록" },
  { text: "실패는 끝이 아니라 시작이다", author: "", category: "인생어록" },
  { text: "매일 작은 진전이 모여 큰 변화가 된다", author: "", category: "인생어록" },
  { text: "비교하지 마라, 나아가라", author: "", category: "인생어록" },
  { text: "내가 원하는 모습으로 살아가라", author: "", category: "인생어록" },
  { text: "웃음이 최고의 선물이다", author: "", category: "인생어록" },
  { text: "감사하는 마음이 행복을 만든다", author: "", category: "인생어록" },
  { text: "시간은 우리의 가장 소중한 자산이다", author: "", category: "인생어록" },
  { text: "작은 일도 소홀하지 마라", author: "", category: "인생어록" },
  { text: "지금이 아니면 언제인가", author: "", category: "인생어록" },
  { text: "부족한 것을 보지 말고 있는 것을 보라", author: "", category: "인생어록" },
  { text: "행동이 말보다 크다", author: "", category: "인생어록" },
  { text: "꿈을 종이에 쓰면 목표가 된다", author: "", category: "인생어록" },
  { text: "매순간이 소중하다", author: "", category: "인생어록" },
  { text: "자신을 믿으라", author: "", category: "인생어록" },
  { text: "올바른 길이 언제나 쉬운 것은 아니다", author: "", category: "인생어록" },
  { text: "혼자가 아니라는 것을 기억하라", author: "", category: "인생어록" },
  { text: "실수는 배움의 기회다", author: "", category: "인생어록" },
  { text: "좋은 습관이 좋은 결과를 만든다", author: "", category: "인생어록" },
  { text: "포기하는 순간이 패배하는 순간이다", author: "", category: "인생어록" },
  { text: "내일의 내가 오늘의 선택을 감사하기를", author: "", category: "인생어록" },
  { text: "완벽하지 않아도 시작하라", author: "", category: "인생어록" },
  { text: "부정적인 생각이 부정적인 결과를 만든다", author: "", category: "인생어록" },
  { text: "용기를 내서 한 발 나아가라", author: "", category: "인생어록" },
  { text: "모든 성공은 작은 것에서 시작된다", author: "", category: "인생어록" },
  { text: "우리의 미래는 지금 결정된다", author: "", category: "인생어록" },
  { text: "사랑하는 사람 곁이 최고의 장소다", author: "", category: "인생어록" },
  { text: "행복은 외부에서 오지 않는다", author: "", category: "인생어록" },
  { text: "이 모든 것이 지나갈 것이다", author: "", category: "인생어록" },
  { text: "춤을 추듯 살아가라", author: "", category: "인생어록" },
  { text: "마음이 여유로우면 모든 것이 아름답다", author: "", category: "인생어록" },
  { text: "좋은 일은 작은 것부터 시작된다", author: "", category: "인생어록" },
  { text: "당신의 존재만으로 충분하다", author: "", category: "인생어록" },
  { text: "가는 길에 꽃이 핀다", author: "", category: "인생어록" },
  { text: "누군가는 당신의 희망이다", author: "", category: "인생어록" },
  { text: "인생은 아름다운 여정이다", author: "", category: "인생어록" },
  { text: "오늘을 살 때 내일이 나타난다", author: "", category: "인생어록" },
  { text: "주어진 것을 감사하라", author: "", category: "인생어록" },
  { text: "마음의 소리를 들어라", author: "", category: "인생어록" },
  { text: "실패는 성공의 일부다", author: "", category: "인생어록" },
  { text: "멈추지 마라, 계속 나아가라", author: "", category: "인생어록" },
  { text: "당신이 변하면 세상도 변한다", author: "", category: "인생어록" },
  { text: "작은 행복을 모으면 큰 행복이 된다", author: "", category: "인생어록" },
  { text: "슬픔도 지나간다", author: "", category: "인생어록" },
  { text: "희망을 잃지 마라", author: "", category: "인생어록" },
  { text: "당신의 이야기가 누군가를 구한다", author: "", category: "인생어록" },
  { text: "좋은 사람과 함께 하라", author: "", category: "인생어록" },
  { text: "오늘이 마지막이라면 어떻게 살겠는가", author: "", category: "인생어록" },
  { text: "미움보다 사랑을 택하라", author: "", category: "인생어록" },
  { text: "모든 것이 결국 잘될 것이다", author: "", category: "인생어록" },
  { text: "아프면 쉬어도 된다", author: "", category: "인생어록" },
  { text: "내 속도로 가면 된다", author: "", category: "인생어록" },
  { text: "완벽함을 추구하지 말고 노력하라", author: "", category: "인생어록" },
  { text: "한 발씩 나아가면 결국 도착한다", author: "", category: "인생어록" },
  { text: "남과 비교하지 말고 어제의 나와 비교하라", author: "", category: "인생어록" },
  { text: "당신은 혼자가 아니다", author: "", category: "인생어록" },
  { text: "꿈을 꾸면 현실이 된다", author: "", category: "인생어록" },
  { text: "용기는 두려움을 이긴다", author: "", category: "인생어록" },
  { text: "인생은 아름다운 모험이다", author: "", category: "인생어록" },
  { text: "현재를 즐겨라", author: "", category: "인생어록" },
  { text: "당신의 노력은 결코 헛되지 않다", author: "", category: "인생어록" },
  { text: "감정도 파도처럼 밀고 빠진다", author: "", category: "인생어록" },
  { text: "힘들 때일수록 웃으려 노력하라", author: "", category: "인생어록" },
  { text: "지금이 가장 소중한 순간이다", author: "", category: "인생어록" },
  { text: "당신의 선택이 당신을 정의한다", author: "", category: "인생어록" },
  { text: "모든 것이 다 되지 않아도 괜찮다", author: "", category: "인생어록" },
  { text: "살아있다는 것 자체가 축복이다", author: "", category: "인생어록" },
  { text: "좋은 추억이 최고의 재산이다", author: "", category: "인생어록" },
  { text: "후회보다 도전을 하라", author: "", category: "인생어록" },
  { text: "버팀목은 항상 곁에 있다", author: "", category: "인생어록" },
  { text: "나약해도 괜찮다", author: "", category: "인생어록" },
  { text: "새로운 날이 또 온다", author: "", category: "인생어록" },
  { text: "상황은 변하지만 당신은 강하다", author: "", category: "인생어록" },
  { text: "모든 계절이 아름답다", author: "", category: "인생어록" },
  { text: "답은 안에 있다", author: "", category: "인생어록" },
  { text: "현재에 충실하면 미래도 좋아진다", author: "", category: "인생어록" },
  { text: "처음부터 잘할 수는 없다", author: "", category: "인생어록" },
  { text: "나를 사랑하는 것부터 시작하라", author: "", category: "인생어록" },
  { text: "시간이 모든 것을 해결하지는 않지만 낫게 만든다", author: "", category: "인생어록" },
  { text: "언제든 시작할 수 있다", author: "", category: "인생어록" },
  { text: "당신의 노력을 믿어라", author: "", category: "인생어록" },
  { text: "문제 있는 사람이 있는 것 아니라 상황이 있을 뿐이다", author: "", category: "인생어록" },
  { text: "스스로를 응원해주라", author: "", category: "인생어록" },
  { text: "어둠 속에도 빛이 있다", author: "", category: "인생어록" },
  { text: "당신이 누군가의 빛이 될 수 있다", author: "", category: "인생어록" },
  { text: "괜찮지 않아도 괜찮다고 말해도 된다", author: "", category: "인생어록" },
  { text: "혼자가 아니라는 걸 기억해", author: "", category: "인생어록" },
  { text: "우리는 함께 강하다", author: "", category: "인생어록" },
  { text: "내일은 다른 날이다", author: "", category: "인생어록" },
  { text: "당신이 있어서 감사하다", author: "", category: "인생어록" },
  { text: "최고의 시간은 지금이다", author: "", category: "인생어록" },
  { text: "앞으로만 가면 된다", author: "", category: "인생어록" },
  { text: "당신은 그럴 자격이 있다", author: "", category: "인생어록" },

  // ── 주식명언 ── (투자 철학, 멘탈 관리, 투자 지혜) [50+개]

  { text: "투자에서 가장 중요한 것은 시간이다", author: "워렌 버핏", category: "주식명언" },
  { text: "두려움과 탐욕이 시장을 움직인다", author: "워렌 버핏", category: "주식명언" },
  { text: "무지해 보이는 것들이 큰 기회다", author: "워렌 버핏", category: "주식명언" },
  { text: "좋은 회사에 낮은 가격으로 들어가는 것이 투자의 정석이다", author: "워렌 버핏", category: "주식명언" },
  { text: "시장이 너를 두려워하게 할 때 용감하게 행동하라", author: "워렌 버핏", category: "주식명언" },
  { text: "포트폴리오는 당신이 이해하는 회사들로만 구성하라", author: "워렌 버핏", category: "주식명언" },
  { text: "장기 투자자는 단기 변동성에 흔들리지 않는다", author: "워렌 버핏", category: "주식명언" },
  { text: "안전마진을 확보하지 않은 투자는 투자가 아니라 투기다", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "기업 분석 없는 주식 매매는 도박이다", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "가격은 임시적이지만 가치는 영원하다", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "시장은 항상 옳지 않다, 그것이 기회다", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "감정이 투자의 적이다", author: "피터 린치", category: "주식명언" },
  { text: "당신이 이해하는 기업에만 투자하라", author: "피터 린치", category: "주식명언" },
  { text: "현금이 왕이다", author: "조지 소로스", category: "주식명언" },
  { text: "시장의 반사성을 이해하는 자가 승자다", author: "조지 소로스", category: "주식명언" },
  { text: "손절매는 투자의 기본이다", author: "조지 소로스", category: "주식명언" },
  { text: "위험을 관리하지 않으면 자본을 잃는다", author: "찰리 멍거", category: "주식명언" },
  { text: "과욕은 패배의 시작이다", author: "찰리 멍거", category: "주식명언" },
  { text: "심플한 사업모델이 최고의 투자처다", author: "찰리 멍거", category: "주식명언" },
  { text: "복리의 힘을 이해하는 자가 부자가 된다", author: "투자 격언", category: "주식명언" },
  { text: "무릎에서 사서 어깨에서 팔아라", author: "투자 격언", category: "주식명언" },
  { text: "열 번 치는 것보다 한 번 맞춰라", author: "투자 격언", category: "주식명언" },
  { text: "시간은 돈이지만 서두르면 손해다", author: "투자 격언", category: "주식명언" },
  { text: "모든 알이 한 바구니에 들어가지 말아야 한다", author: "투자 격언", category: "주식명언" },
  { text: "시장을 이기려 하지 말고 함께하라", author: "존 보글", category: "주식명언" },
  { text: "낮은 수수료가 높은 수익을 만든다", author: "존 보글", category: "주식명언" },
  { text: "패시브 투자가 장기 수익을 보장한다", author: "존 보글", category: "주식명언" },
  { text: "변동성은 약점이 아니라 기회다", author: "나심 탈레브", category: "주식명언" },
  { text: "블랙스완에 대비하는 자가 살아남는다", author: "나심 탈레브", category: "주식명언" },
  { text: "소수가 전체 수익을 만든다", author: "켄 피셔", category: "주식명언" },
  { text: "기업의 펀더멘탈이 모든 것을 결정한다", author: "필립 피셔", category: "주식명언" },
  { text: "좋은 회사는 시간이 지나도 좋은 회사다", author: "필립 피셔", category: "주식명언" },
  { text: "시장의 부자는 침착함으로 만들어진다", author: "존 템플턴", category: "주식명언" },
  { text: "최악의 시기가 최고의 투자 시점이다", author: "존 템플턴", category: "주식명언" },
  { text: "욕심을 버리면 손실도 줄어든다", author: "존 템플턴", category: "주식명언" },
  { text: "가치 투자자는 서서히 그리고 꾸준히 간다", author: "하워드 막스", category: "주식명언" },
  { text: "시장의 주기를 읽는 자가 투자자다", author: "하워드 막스", category: "주식명언" },
  { text: "남과 다를 용기가 초과 수익을 만든다", author: "하워드 막스", category: "주식명언" },
  { text: "현금 흐름이 곧 가치다", author: "레이 달리오", category: "주식명언" },
  { text: "리스크 관리가 성공의 열쇠다", author: "레이 달리오", category: "주식명언" },
  { text: "분산 투자로 리스크를 줄여라", author: "레이 달리오", category: "주식명언" },
  { text: "주식시장은 확률의 게임이다", author: "마크 미너바인", category: "주식명언" },
  { text: "감정 없는 매매가 성공의 조건이다", author: "존 리", category: "주식명언" },
  { text: "장기 목표를 잃으면 단기 변동에 흔들린다", author: "존 리", category: "주식명언" },
  { text: "주식은 회사의 일부를 소유하는 것이다", author: "박경철", category: "주식명언" },
  { text: "공부하지 않은 투자는 도박이다", author: "박경철", category: "주식명언" },
  { text: "매매 빈도가 높을수록 수익은 낮아진다", author: "투자 격언", category: "주식명언" },
  { text: "시간과 복리가 최고의 투자 도구다", author: "투자 격언", category: "주식명언" },
  { text: "손실 회피는 성장의 장애물이다", author: "투자 격언", category: "주식명언" },
  { text: "급하면 망한다는 투자의 법칙을 기억하라", author: "투자 격언", category: "주식명언" },

  // ── 원피스명언 ── (ONE PIECE 한글 명대사) [40+개]

  { text: "계획대로 될 리 없지 그게 항해 아니야!", author: "루피", category: "원피스명언" },
  { text: "해적왕이 되는 남이다!", author: "루피", category: "원피스명언" },
  { text: "나는 당신이 뭘 했는지 모른다 하지만 죽고 싶지 않으면 싸워!", author: "루피", category: "원피스명언" },
  { text: "가슴의 크기로 꿈의 크기가 정해진다!", author: "루피", category: "원피스명언" },
  { text: "친구를 잃는 건 죽는 것보다 힘들어", author: "루피", category: "원피스명언" },
  { text: "무릎을 꿇고는 살 수 없어!", author: "조로", category: "원피스명언" },
  { text: "남자라는 게 뭔지 보여주겠어!", author: "조로", category: "원피스명언" },
  { text: "죽음도 겁내지 않는데 남을 잃는 게 무섭다", author: "조로", category: "원피스명언" },
  { text: "내 꿈을 포기할 수 없다!", author: "조로", category: "원피스명언" },
  { text: "검을 잃으면 손으로 싸운다", author: "조로", category: "원피스명언" },
  { text: "신사의 집념을 시험하지 말아야 해", author: "상디", category: "원피스명언" },
  { text: "여성을 함부로 대할 수 없지", author: "상디", category: "원피스명언" },
  { text: "살찐 여자가 최고야", author: "상디", category: "원피스명언" },
  { text: "꿈은 높을수록 좋아", author: "상디", category: "원피스명언" },
  { text: "나는 지옥도 헤쳐 나갈 거야", author: "상디", category: "원피스명언" },
  { text: "돈과 보물은 이 세상에서 가장 쉽게 구할 수 있어", author: "나미", category: "원피스명언" },
  { text: "뭐든 할 수 있어, 나미니까!", author: "나미", category: "원피스명언" },
  { text: "돈 없이 꿈을 꿀 수 없어!", author: "나미", category: "원피스명언" },
  { text: "거짓말도 때론 필요해", author: "우솝", category: "원피스명언" },
  { text: "나는 용감한 해적 우솝이다!", author: "우솝", category: "원피스명언" },
  { text: "거짓말은 의욕의 근원이야", author: "우솝", category: "원피스명언" },
  { text: "하고 싶은 일이 있으면 꼭 실현해야 해", author: "로빈", category: "원피스명언" },
  { text: "나는 살아있어도 괜찮아?", author: "로빈", category: "원피스명언" },
  { text: "역사는 항상 그렇게 조작된다", author: "로빈", category: "원피스명언" },
  { text: "배는 우리의 꿈이야", author: "프랑키", category: "원피스명언" },
  { text: "남자라면 가슴을 펼쳐야 한다!", author: "프랑키", category: "원피스명언" },
  { text: "슈퍼~!", author: "프랑키", category: "원피스명언" },
  { text: "죽자 이 몸 악의 바다로~", author: "브룩", category: "원피스명언" },
  { text: "혼은 나약하지 않아", author: "브룩", category: "원피스명언" },
  { text: "다시 한 번 살아가는 것도 나쁘지 않아", author: "에이스", category: "원피스명언" },
  { text: "나는 아무도 나를 욕하게 두지 않을 거야", author: "에이스", category: "원피스명언" },
  { text: "해적왕의 아들이면 뭐하나", author: "에이스", category: "원피스명언" },
  { text: "꿈을 쫓는 것은 죄가 아니야", author: "샹크스", category: "원피스명언" },
  { text: "어린 후배여 계속 나아가거라", author: "실버즈 레일리", category: "원피스명언" },
  { text: "이 해에는 절대자가 없다", author: "화이트비어드", category: "원피스명언" },
  { text: "가족의 대의를 위해서라면", author: "화이트비어드", category: "원피스명언" },
  { text: "자유야말로 이 세상에서 가장 아름다운 것이다", author: "골드 로저", category: "원피스명언" },
  { text: "죽이러 오는 놈은 온다", author: "로", category: "원피스명언" },
  { text: "약한 자는 죽으면 그만이다", author: "도플라밍고", category: "원피스명언" },
  { text: "변화의 바람이 분다", author: "사보", category: "원피스명언" },

  // ── 주식명언 추가 ── [+100개]

  { text: "시장에 완벽한 진입점은 없다", author: "워렌 버핏", category: "주식명언" },
  { text: "평생 주식으로 먹고산다고 생각하지 마라", author: "워렌 버핏", category: "주식명언" },
  { text: "좋은 주식을 저가에 사는 것이 투자의 기본이다", author: "워렌 버핏", category: "주식명언" },
  { text: "주식시장은 금전적 이득을 위한 기계가 아니다", author: "워렌 버핏", category: "주식명언" },
  { text: "돈은 도구일 뿐 목표가 아니다", author: "워렌 버핏", category: "주식명언" },
  { text: "이익이 남으면 욕심내지 말고 팔아라", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "손실의 두려움이 투자 결정을 지배한다", author: "벤저민 그레이엠", category: "주식명언" },
  { text: "안전마진이 없는 투자는 투기다", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "가치보다 가격이 높으면 사지 마라", author: "벤저민 그레이엠", category: "주식명언" },
  { text: "단기적 변동은 무시하고 장기를 보라", author: "벤저민 그레이엠", category: "주식명언" },
  { text: "분석 없는 매매는 자살 행위다", author: "필립 피셔", category: "주식명언" },
  { text: "회사를 알지 못하면 주식을 사지 마라", author: "필립 피셔", category: "주식명언" },
  { text: "위대한 회사의 주식을 오래 보유하라", author: "필립 피셔", category: "주식명언" },
  { text: "주식은 종이 자산이 아니라 회사의 소유권이다", author: "피터 린치", category: "주식명언" },
  { text: "당신이 이해할 수 있는 회사의 주식만 사라", author: "피터 린치", category: "주식명언" },
  { text: "시장의 과열에 휩쓸리지 마라", author: "피터 린치", category: "주식명언" },
  { text: "연구와 인내가 투자의 기본이다", author: "피터 린치", category: "주식명언" },
  { text: "좋은 회사를 저렴하게 사면 반은 성공한 것이다", author: "찰리 멍거", category: "주식명언" },
  { text: "집중 투자가 최고의 전략이다", author: "찰리 멍거", category: "주식명언" },
  { text: "실수를 피하면 성공이 따라온다", author: "찰리 멍거", category: "주식명언" },
  { text: "지혜롭게 기다리는 것이 투자의 핵심이다", author: "찰리 멍거", category: "주식명언" },
  { text: "리스크는 무지에서 비롯된다", author: "찰리 멍거", category: "주식명언" },
  { text: "시장 변동은 기회를 제공한다", author: "하워드 막스", category: "주식명언" },
  { text: "모든 투자자는 실수한다", author: "하워드 막스", category: "주식명언" },
  { text: "위험을 이해하지 못하는 자는 망한다", author: "하워드 막스", category: "주식명언" },
  { text: "타이밍을 맞추려고 하지 말아라", author: "하워드 막스", category: "주식명언" },
  { text: "현금은 왕이다", author: "레이 달리오", category: "주식명언" },
  { text: "포트폴리오는 분산된 베팅이다", author: "레이 달리오", category: "주식명언" },
  { text: "예측 불가능한 것을 예측하려 하지 마라", author: "레이 달리오", category: "주식명언" },
  { text: "원칙을 따르는 자가 승리한다", author: "레이 달리오", category: "주식명언" },
  { text: "시장이 아래로 내려갈 때가 사는 시점이다", author: "조지 소로스", category: "주식명언" },
  { text: "트렌드를 따르되 추종하지 마라", author: "조지 소로스", category: "주식명언" },
  { text: "착각에서 비롯된 수익도 있다", author: "조지 소로스", category: "주식명언" },
  { text: "자신의 가정을 의심하라", author: "조지 소로스", category: "주식명언" },
  { text: "패턴 인식이 투자의 열쇠다", author: "조지 소로스", category: "주식명언" },
  { text: "시장을 이기려 하지 말고 함께하라", author: "앙드레 코스톨라니", category: "주식명언" },
  { text: "돈은 심리 게임이다", author: "앙드레 코스톨라니", category: "주식명언" },
  { text: "물가 상승을 무시하는 투자자는 망한다", author: "앙드레 코스톨라니", category: "주식명언" },
  { text: "저점에서 사고 고점에서 판다는 건 이론일 뿐이다", author: "앙드레 코스톨라니", category: "주식명언" },
  { text: "뉴스를 기반으로 거래하지 마라", author: "존 보글", category: "주식명언" },
  { text: "인덱스 펀드가 최선의 선택이다", author: "존 보글", category: "주식명언" },
  { text: "적절한 비용이 수익의 절반이다", author: "존 보글", category: "주식명언" },
  { text: "장기 투자가 승리한다", author: "존 보글", category: "주식명언" },
  { text: "통계는 거짓말을 한다", author: "나심 탈레브", category: "주식명언" },
  { text: "검은 백조는 예상하지 못한 곳에서 나타난다", author: "나심 탈레브", category: "주식명언" },
  { text: "불확실성이 최고의 보험이다", author: "나심 탈레브", category: "주식명언" },
  { text: "극단적인 변화를 대비하라", author: "나심 탈레브", category: "주식명언" },
  { text: "수익률보다 손실률이 중요하다", author: "세스 클라만", category: "주식명언" },
  { text: "잃지 않는 것이 성공이다", author: "세스 클라만", category: "주식명언" },
  { text: "가치 투자는 장기 게임이다", author: "세스 클라만", category: "주식명언" },
  { text: "시장의 광기를 이용하라", author: "조엘 그린블라트", category: "주식명언" },
  { text: "간단한 전략이 최고다", author: "조엘 그린블라트", category: "주식명언" },
  { text: "회사의 성장성을 무시하지 마라", author: "조엘 그린블라트", category: "주식명언" },
  { text: "실패는 배움의 기회다", author: "제시 리버모어", category: "주식명언" },
  { text: "시장 심리를 읽는 자가 승자다", author: "제시 리버모어", category: "주식명언" },
  { text: "감정은 투자의 적이다", author: "제시 리버모어", category: "주식명언" },
  { text: "기술적 분석도 중요하다", author: "제시 리버모어", category: "주식명언" },
  { text: "흐름을 타는 것이 이익이다", author: "마크 미너비니", category: "주식명언" },
  { text: "주식은 모멘텀이 있을 때 사라", author: "마크 미너비니", category: "주식명언" },
  { text: "약한 회사는 피하라", author: "마크 미너비니", category: "주식명언" },
  { text: "숨겨진 보물을 찾는 일이 투자다", author: "윌리엄 오닐", category: "주식명언" },
  { text: "최고 성장주를 추적하라", author: "윌리엄 오닐", category: "주식명언" },
  { text: "과거의 패턴은 미래를 말한다", author: "윌리엄 오닐", category: "주식명언" },
  { text: "손실을 빨리 인정하고 떠나라", author: "윌리엄 오닐", category: "주식명언" },
  { text: "큰 수익은 큰 위험에서 나온다", author: "켄 피셔", category: "주식명언" },
  { text: "다양한 시각으로 분석하라", author: "켄 피셔", category: "주식명언" },
  { text: "일반적인 생각에 반대하라", author: "켄 피셔", category: "주식명언" },
  { text: "기금 규모가 성과를 보장하지 않는다", author: "모니시 파브라이", category: "주식명언" },
  { text: "장기 가치를 중시하라", author: "모니시 파브라이", category: "주식명언" },
  { text: "분석적 사고로 자신감을 가져라", author: "모니시 파브라이", category: "주식명언" },
  { text: "주식의 실적이 가격을 따라잡는다", author: "투자 격언", category: "주식명언" },
  { text: "비용이 수익을 잠식한다", author: "투자 격언", category: "주식명언" },
  { text: "탐욕은 손실을 부른다", author: "투자 격언", category: "주식명언" },
  { text: "분산이 안전 장치다", author: "투자 격언", category: "주식명언" },
  { text: "인내가 보상을 낳는다", author: "투자 격언", category: "주식명언" },
  { text: "기록을 남기고 검토하라", author: "투자 격언", category: "주식명언" },
  { text: "작은 손실은 큰 손실로 간다", author: "투자 격言", category: "주식명언" },
  { text: "공포에 사고 탐욕에 팔아라", author: "투자 격言", category: "주식명언" },
  { text: "시장은 항상 옳다", author: "투자 격언", category: "주식명언" },
  { text: "우량주 장기 보유가 최고다", author: "존 리", category: "주식명언" },
  { text: "주식 투자를 인생의 일부로 봐라", author: "존 리", category: "주식명언" },
  { text: "수익률에 집착하지 마라", author: "존 리", category: "주식명언" },
  { text: "투자는 수학이 아니라 심리다", author: "박경철", category: "주식명언" },
  { text: "기대감이 아니라 현실을 봐라", author: "박경철", category: "주식명언" },
  { text: "주식은 꾸준함의 게임이다", author: "박경철", category: "주식명언" },
  { text: "나쁜 시황도 좋은 기회다", author: "박경철", category: "주식명언" },
  { text: "투자 일지는 당신의 스승이다", author: "투자 격언", category: "주식명언" },
  { text: "비합리적인 행동이 손실을 만든다", author: "투자 격언", category: "주식명언" },
  { text: "계획 없는 매매는 패배다", author: "투자 격언", category: "주식명언" },

  // ── 외국명언 추가 ── [+80개]

  { text: "가장 큰 적은 자신의 두려움이다", author: "랜디 파우시", category: "외국명언" },
  { text: "꿈은 자유로운 곳에서 자란다", author: "에밀리 디킨슨", category: "외국명언" },
  { text: "성공의 정의는 사람마다 다르다", author: "오프라 윈프리", category: "외국명언" },
  { text: "실패 없이 성공도 없다", author: "제임스 다이슨", category: "외국명언" },
  { text: "작은 것부터 시작하면 크게 자란다", author: "알렉산더 해밀턴", category: "외국명언" },
  { text: "인생은 자신이 만드는 것이다", author: "조지 버나드 쇼", category: "외국명언" },
  { text: "아무것도 불가능하지 않다", author: "무하마드 알리", category: "외국명언" },
  { text: "오늘의 선택이 내일을 정한다", author: "조언 우든", category: "외국명언" },
  { text: "두려움은 착각일 뿐이다", author: "프랭크 허버드", category: "외국명언" },
  { text: "성공은 실패의 연속이다", author: "콜린 파월", category: "외국명언" },
  { text: "희망 없이는 살 수 없다", author: "마리아 몬테소리", category: "외국명언" },
  { text: "변화가 없으면 진보도 없다", author: "제임스 제크슨", category: "외국명언" },
  { text: "용기란 두려움 속에서 행동하는 것이다", author: "마크 트웨인", category: "외국명언" },
  { text: "삶은 자신이 만드는 거다", author: "로버트 프로스트", category: "외국명언" },
  { text: "완벽함을 추구하지 말고 나아가라", author: "존 카맥", category: "외국명언" },
  { text: "자신을 믿는 것이 절반이다", author: "시어도어 루즈벨트", category: "외국명언" },
  { text: "실패는 다시 시작할 기회다", author: "헨리 포드", category: "외국명언" },
  { text: "꿈을 크게 꾸라", author: "월트 디즈니", category: "외국명언" },
  { text: "미래는 자신이 만드는 것이다", author: "아이작 뉴턴", category: "외국명언" },
  { text: "작은 일을 크게 하라", author: "마더 테레사", category: "외국명언" },
  { text: "모든 것은 가능하다", author: "오프라 윈프리", category: "외국명언" },
  { text: "현재에 집중하라", author: "에크하르트 톨레", category: "외국명언" },
  { text: "자신의 목소리를 찾아라", author: "조셉 캠벨", category: "외국명언" },
  { text: "성공은 내부에서 온다", author: "스티부 조브스", category: "외국명언" },
  { text: "매일이 새로운 시작이다", author: "볼프강 폰 괴테", category: "외국명언" },
  { text: "행동이 말보다 크다", author: "벤저민 프랭클린", category: "외국명언" },
  { text: "지식이 힘이다", author: "모한다스 간디", category: "외국명언" },
  { text: "긍정이 모든 것을 바꾼다", author: "노먼 빈센트 필", category: "외국명언" },
  { text: "인생은 예술이다", author: "오스카 와일드", category: "외국명언" },
  { text: "내일은 없다, 오늘만 있다", author: "카시우스 클레이", category: "외국명언" },
  { text: "나는 할 수 있다고 생각한다", author: "헨리 포드", category: "외국명언" },
  { text: "모든 것이 가능하다는 것을 믿어라", author: "월트 디즈니", category: "외국명언" },
  { text: "삶은 모험이다", author: "헬렌 켈러", category: "외국명언" },
  { text: "성공은 선택이다", author: "티모시 페리스", category: "외국명언" },
  { text: "감정이 아닌 이성으로 행동하라", author: "스토아 철학", category: "외국명언" },
  { text: "깊은 숨을 쉬고 계속 나아가라", author: "조지 버나드 쇼", category: "외국명언" },
  { text: "마음이 원하는 것을 하라", author: "조셉 머피", category: "외국명언" },
  { text: "오늘 할 수 있는 것을 내일로 미루지 마라", author: "벤저민 프랭클린", category: "외국명언" },
  { text: "자신을 사랑하는 것부터 시작하라", author: "루이즈 �이", category: "외국명언" },
  { text: "작은 일의 연속이 큰 성공을 만든다", author: "제임스 클리어", category: "외국명언" },
  { text: "독서는 영혼의 양식이다", author: "스티브 잡스", category: "외국명언" },
  { text: "묻지 말고 행동하라", author: "나이크 슬로건", category: "외국명언" },
  { text: "지혜는 경험에서 온다", author: "프란시스 베이컨", category: "외국명언" },
  { text: "모든 것은 변한다", author: "헤라클리토스", category: "외국명언" },
  { text: "침묵은 금이다", author: "톰 헹크스", category: "외국명언" },
  { text: "매일 조금씩 나아가라", author: "제임스 클리어", category: "외국명언" },
  { text: "자신을 초대하지 말고 자신을 만들어라", author: "조건 트레이시", category: "외국명언" },
  { text: "운은 준비된 자에게만 온다", author: "데일 카네기", category: "외국명언" },
  { text: "꿈꾸고 계획하고 행동하라", author: "월트 디즈니", category: "외국명언" },
  { text: "생각이 현실을 만든다", author: "제임스 앨런", category: "외국명언" },
  { text: "삶은 짧다 이를 소중히 하라", author: "스티브 잡스", category: "외국명언" },
  { text: "자신의 진정한 목소리를 찾아라", author: "사이먼 시넥", category: "외국명언" },
  { text: "모든 것이 불가능해 보일 때가 시작이다", author: "무하마드 알리", category: "외국명언" },
  { text: "현재 순간이 전부다", author: "에크하르트 톨레", category: "외국명언" },
  { text: "교육이 미래를 만든다", author: "넬슨 만델라", category: "외국명언" },
  { text: "성장에 끝은 없다", author: "짐 론", category: "외국명언" },
  { text: "좋은 친구가 최고의 재산이다", author: "랄프 왈도 에머슨", category: "외국명언" },
  { text: "마음의 평온이 가장 큰 부다", author: "마르쿠스 아우렐리우스", category: "외국명언" },
  { text: "실패는 당신을 강하게 만든다", author: "제이 지", category: "외국명언" },
  { text: "자신을 아는 것이 진정한 지혜다", author: "소크라테스", category: "외국명언" },
  { text: "매일 배우는 자가 승리한다", author: "빌 게이츠", category: "외국명언" },
  { text: "사랑이 모든 것을 치유한다", author: "오프라 윈프리", category: "외국명언" },
  { text: "작은 것부터 시작하라", author: "짐 론", category: "외국명언" },
  { text: "자신을 신뢰하라", author: "라깝 칼리", category: "외국명언" },
  { text: "삶은 선택의 연속이다", author: "장 폴 사르트르", category: "외국명언" },
  { text: "현실을 직시하고 나아가라", author: "짐 콜린스", category: "외국명언" },
  { text: "성공은 작은 노력의 누적이다", author: "제임스 클리어", category: "외국명언" },
  { text: "마음을 비우면 모든 것이 들어온다", author: "선불교 명언", category: "외국명언" },
  { text: "인생에서 가장 중요한 것은 관계다", author: "하버드 성인발달연구", category: "외국명언" },
  { text: "오늘이 내일을 결정한다", author: "빌 더란", category: "외국명언" },
  { text: "무서움은 성장의 신호다", author: "슈잔 제퍼드", category: "외국명언" },

  // ── 한국명언 추가 ── [+70개]

  { text: "한 번의 실패도 다시 일어날 수 있는 기회다", author: "박종범", category: "한국명언" },
  { text: "청소년이 국가의 미래다", author: "이순신", category: "한국명언" },
  { text: "겸손함이 가장 큰 강함이다", author: "김구", category: "한국명언" },
  { text: "깊이 있는 사람이 된다면", author: "함석헌", category: "한국명언" },
  { text: "매일 조금씩 나아가는 것이 성공이다", author: "박재범", category: "한국명언" },
  { text: "가족과 나라 중에 나라를 택하는 것이 선비다", author: "이황", category: "한국명언" },
  { text: "내가 못 하는 것을 다른 사람이 한다", author: "정도전", category: "한국명언" },
  { text: "현명함은 언제나 단순함 속에 있다", author: "서경석", category: "한국명언" },
  { text: "행동이 모든 것을 증명한다", author: "안창호", category: "한국명언" },
  { text: "자신감이 없으면 시작도 못 한다", author: "박종범", category: "한국명언" },
  { text: "겨울이 오면 봄도 온다", author: "안창호", category: "한국명언" },
  { text: "충돈하지 않으려면 성장이 없다", author: "이덕환", category: "한국명언" },
  { text: "작은 것을 소홀히 하지 않는 것이 큼이다", author: "박순일", category: "한국명언" },
  { text: "진실이 가장 큰 힘이다", author: "김구", category: "한국명언" },
  { text: "공부는 나를 위함이 아니라 나라를 위함이다", author: "율곡이이", category: "한국명언" },
  { text: "스스로를 버린 자만이 성공한다", author: "이순신", category: "한국명언" },
  { text: "어려움 속에서 피어난 꽃이 가장 아름답다", author: "김구", category: "한국명언" },
  { text: "화를 낼 것이 아니라 고쳐야 한다", author: "세종대왕", category: "한국명언" },
  { text: "전략 없는 노력은 낭비다", author: "이순신", category: "한국명언" },
  { text: "마음이 곧 세상이다", author: "구재서", category: "한국명언" },
  { text: "불의에 저항하는 것이 의무다", author: "김구", category: "한국명언" },
  { text: "미래는 현재의 선택으로 만들어진다", author: "박경철", category: "한국명언" },
  { text: "진정성이 사람을 움직인다", author: "정주영", category: "한국명언" },
  { text: "감사하는 마음이 성공의 기초다", author: "이병철", category: "한국명언" },
  { text: "포기하는 순간 모든 게 끝난다", author: "정주영", category: "한국명언" },
  { text: "절망 속에서도 희망을 찾는 것이 선비다", author: "한용운", category: "한국명언" },
  { text: "시간을 낭비하는 것은 인생을 낭비하는 것이다", author: "이병철", category: "한국명언" },
  { text: "자신을 이기는 것이 참된 승리다", author: "이순신", category: "한국명언" },
  { text: "작은 일에서 큰 가치를 찾아라", author: "박순일", category: "한국명언" },
  { text: "올바른 마음이 모든 것을 결정한다", author: "율곡이이", category: "한국명언" },
  { text: "후회 없이 사는 것이 가장 큰 행복이다", author: "함석헌", category: "한국명언" },
  { text: "진정한 부는 마음의 풍요로움이다", author: "김구", category: "한국명언" },
  { text: "단순함이 가장 강한 힘이다", author: "박재범", category: "한국명언" },
  { text: "매일 새로운 마음으로 시작하라", author: "안창호", category: "한국명언" },
  { text: "모두가 주인이 되는 세상을 위해", author: "김구", category: "한국명언" },
  { text: "자신의 역할에 충실한 것이 가장 큰 성공이다", author: "신사임당", category: "한국명언" },
  { text: "약속을 지키는 것이 신용이다", author: "이병철", category: "한국명언" },
  { text: "겸허함으로 배우고 진취심으로 행동하라", author: "박정희", category: "한국명언" },
  { text: "어려울수록 희망을 잃지 말아야 한다", author: "윤동주", category: "한국명언" },
  { text: "현재를 소중히 여기는 것이 미래를 만든다", author: "함석헌", category: "한국명언" },
  { text: "마음먹은 것을 반드시 이루자", author: "이순신", category: "한국명언" },
  { text: "뜨거운 열정과 차가운 이성의 조화", author: "안창호", category: "한국명언" },
  { text: "작은 것부터 성실하게 하는 것이 국가 발전의 기초다", author: "박정희", category: "한국명언" },
  { text: "영혼의 자유가 가장 중요하다", author: "한용운", category: "한국명언" },
  { text: "진리를 추구하는 것이 참된 학문이다", author: "정약용", category: "한국명언" },
  { text: "백성의 행복이 나라의 번영이다", author: "세종대왕", category: "한국명언" },
  { text: "실패는 성공의 어머니다", author: "정주영", category: "한국명언" },
  { text: "현명함은 배움에서 온다", author: "퇴계이황", category: "한국명언" },
  { text: "모든 것을 혼자 할 수는 없다", author: "김구", category: "한국명언" },
  { text: "지속적인 노력만이 꿈을 현실로 만든다", author: "박경철", category: "한국명언" },
  { text: "대의를 위해 개인을 버릴 수 있는 용기", author: "안중근", category: "한국명언" },
  { text: "분명한 신념이 미래를 만든다", author: "이순신", category: "한국명언" },
  { text: "내일의 나는 오늘의 선택이 만든다", author: "함석헌", category: "한국명언" },
  { text: "진정성이 없으면 신용도 없다", author: "이병철", category: "한국명언" },
  { text: "어제를 후회하지 말고 내일을 준비하라", author: "정주영", category: "한국명언" },
  { text: "작은 성공의 연속이 큰 성공을 만든다", author: "박정희", category: "한국명언" },
  { text: "모두를 위한 경영이 진정한 경영이다", author: "이병철", category: "한국명언" },
  { text: "희망은 절망을 이긴다", author: "김구", category: "한국명언" },
  { text: "자신을 돌보는 것도 중요하다", author: "함석헌", category: "한국명언" },
  { text: "실천 없는 공부는 장난이다", author: "율곡이이", category: "한국명언" },
  { text: "감정을 다스리는 것이 지혜다", author: "퇴계이황", category: "한국명언" },
  { text: "모든 인생은 존귀하다", author: "한용운", category: "한국명언" },
  { text: "지금이 가장 중요한 순간이다", author: "안창호", category: "한국명언" },
  { text: "진정한 리더는 섬기는 사람이다", author: "이순신", category: "한국명언" },

  // ── 연예인명언 추가 ── [+60개]

  { text: "모든 순간이 소중하다", author: "아이유", category: "연예인명언" },
  { text: "자신을 믿는 것이 첫걸음이다", author: "박수진", category: "연예인명언" },
  { text: "실수는 배움의 기회다", author: "강동원", category: "연예인명언" },
  { text: "감사하는 마음을 잃지 마라", author: "수지", category: "연예인명언" },
  { text: "노력은 절대 배신하지 않는다", author: "박지성", category: "연예인명언" },
  { text: "항상 배우는 마음으로 살아라", author: "이제훈", category: "연예인명언" },
  { text: "작은 행복을 소중히 하라", author: "박진영", category: "연예인명언" },
  { text: "긍정적인 에너지가 모든 것을 바꾼다", author: "이지은", category: "연예인명언" },
  { text: "건강이 가장 큰 자산이다", author: "김탄", category: "연예인명언" },
  { text: "하나를 깊이 있게 하는 것이 낫다", author: "이병헌", category: "연예인명언" },
  { text: "겸손함이 성공을 지킨다", author: "정보석", category: "연예인명언" },
  { text: "꾸준함이 천재를 이긴다", author: "박은빈", category: "연예인명언" },
  { text: "자신의 가치를 아는 것이 중요하다", author: "박보영", category: "연예인명언" },
  { text: "현재 순간을 즐겨라", author: "유연석", category: "연예인명언" },
  { text: "실패를 두려워하지 마라", author: "고현정", category: "연예인명언" },
  { text: "나만의 길을 가야 한다", author: "현빈", category: "연예인명언" },
  { text: "사람이 최고의 자산이다", author: "이문식", category: "연예인명언" },
  { text: "도전이 없으면 성장도 없다", author: "박민지", category: "연예인명언" },
  { text: "웃음의 가치는 말할 수 없다", author: "조인성", category: "연예인명언" },
  { text: "매일 새로운 시작을 하라", author: "한효주", category: "연예인명언" },
  { text: "자신감은 행동에서 온다", author: "류승룡", category: "연예인명언" },
  { text: "좋은 친구가 행복을 만든다", author: "김혜수", category: "연예인명언" },
  { text: "진정성이 모든 것을 이긴다", author: "주진모", category: "연예인명언" },
  { text: "완벽하지 않아도 충분하다", author: "오정해", category: "연예인명언" },
  { text: "시간을 낭비하지 마라", author: "변우석", category: "연예인명언" },
  { text: "열정이 식으면 끝이다", author: "김태희", category: "연예인명언" },
  { text: "올바른 마음가짐이 중요하다", author: "이정재", category: "연예인명언" },
  { text: "포기는 선택이 아니다", author: "공유", category: "연예인명언" },
  { text: "작은 것부터 소중히 하라", author: "김은숙", category: "연예인명언" },
  { text: "성공은 하루아침이 아니다", author: "조정석", category: "연예인명언" },
  { text: "무한의 가능성을 믿어라", author: "박신혜", category: "연예인명언" },
  { text: "나 자신과 화해하는 것이 먼저다", author: "이동욱", category: "연예인명언" },
  { text: "꿈을 버리지 마라", author: "김지원", category: "연예인명언" },
  { text: "도움을 청하는 것도 힘이다", author: "명세균", category: "연예인명언" },
  { text: "성실함이 신뢰를 만든다", author: "오시영", category: "연예인명언" },
  { text: "긍정적인 태도가 앞으로 나아가는 힘이다", author: "엄지원", category: "연예인명언" },
  { text: "자신의 속도를 존중하라", author: "이특", category: "연예인명언" },
  { text: "스트레스는 신호다", author: "한보름", category: "연예인명언" },
  { text: "삶의 질은 선택의 연속이다", author: "오늘의", category: "연예인명언" },
  { text: "모두 같은 속도로 가지 않는다", author: "강문경", category: "연예인명언" },
  { text: "성장에 지름길은 없다", author: "한일",ategory: "연예인명언" },
  { text: "자신을 사랑하기 시작하라", author: "김정환", category: "연예인명언" },
  { text: "매순간이 중요하다", author: "박명수", category: "연예인명언" },
  { text: "함께하는 것이 강함이다", author: "이성민", category: "연예인명언" },
  { text: "희망을 잃지 마라", author: "정현주", category: "연예인명언" },
  { text: "현재를 충실히 살아라", author: "이목", category: "연예인명언" },
  { text: "배움은 평생 과제다", author: "박인우", category: "연예인명언" },
  { text: "내가 가진 것을 감사하라", author: "황정음", category: "연예인명언" },
  { text: "실패도 과정이다", author: "김석훈", category: "연예인명언" },
  { text: "최선을 다하는 것이 최고다", author: "이지홍", category: "연예인명언" },
  { text: "관계를 소중히 하라", author: "서지혜", category: "연예인명언" },

  // ── 인생어록 추가 ── [+60개]

  { text: "너무 깊이 생각하지 말고 앞으로 나아가라", author: "", category: "인생어록" },
  { text: "오늘의 작은 진전이 내일의 성공이다", author: "", category: "인생어록" },
  { text: "잘못된 길도 경험이다", author: "", category: "인생어록" },
  { text: "자신을 위해 최선을 다해라", author: "", category: "인생어록" },
  { text: "완벽함은 존재하지 않는다", author: "", category: "인생어록" },
  { text: "매 순간이 선택이다", author: "", category: "인생어록" },
  { text: "행복은 외부에서 얻는 게 아니라 만드는 것이다", author: "", category: "인생어록" },
  { text: "나약함도 강함이 될 수 있다", author: "", category: "인생어록" },
  { text: "마음이 편해야 모든 것이 잘 보인다", author: "", category: "인생어록" },
  { text: "작은 나이도 큰 꿈을 꿀 수 있다", author: "", category: "인생어록" },
  { text: "솔직함이 가장 예쁘다", author: "", category: "인생어록" },
  { text: "어제의 나를 판단하지 말아라", author: "", category: "인생어록" },
  { text: "현재의 고통도 시간이 흘러가면 추억이 된다", author: "", category: "인생어록" },
  { text: "혼자가 아니라는 것을 알자", author: "", category: "인생어록" },
  { text: "좋은 선택의 연속이 좋은 삶을 만든다", author: "", category: "인생어록" },
  { text: "작은 기쁨이 모여 큰 행복이 된다", author: "", category: "인생어록" },
  { text: "자신을 먼저 돌봐야 남도 도울 수 있다", author: "", category: "인생어록" },
  { text: "꿈을 종이에 쓰고 한 걸음씩 나아가라", author: "", category: "인생어록" },
  { text: "모든 것이 다 해결되지 않아도 살아간다", author: "", category: "인생어록" },
  { text: "시간이 모든 상처를 치유한다", author: "", category: "인생어록" },
  { text: "오늘을 최선으로 살면 내일은 저절로 온다", author: "", category: "인생어록" },
  { text: "작은 목표부터 이루어라", author: "", category: "인생어록" },
  { text: "당신의 노력은 누군가 본다", author: "", category: "인생어록" },
  { text: "계획도 좋지만 현재에 충실하라", author: "", category: "인생어록" },
  { text: "세상은 더 아름다운 사람들로 가득하다", author: "", category: "인생어록" },
  { text: "절망도 지나간다", author: "", category: "인생어록" },
  { text: "내 안의 빛을 믿어라", author: "", category: "인생어록" },
  { text: "변화를 두려워하지 말아라", author: "", category: "인생어록" },
  { text: "한 걸음씩이 모여 먼 길이 된다", author: "", category: "인생어록" },
  { text: "자신의 가치를 아는 것부터 시작하라", author: "", category: "인생어록" },
  { text: "겸손한 마음이 더 많은 것을 배우게 한다", author: "", category: "인생어록" },
  { text: "모든 것은 결과가 아니라 과정이 중요하다", author: "", category: "인생어록" },
  { text: "나를 사랑하는 것이 가장 큰 힘이다", author: "", category: "인생어록" },
  { text: "현재의 순간이 가장 값진 순간이다", author: "", category: "인생어록" },
  { text: "좋은 사람과의 관계가 행복을 만든다", author: "", category: "인생어록" },
  { text: "무한한 가능성은 당신 안에 있다", author: "", category: "인생어록" },
  { text: "지금의 고생이 나중의 행복이 된다", author: "", category: "인생어록" },
  { text: "당신은 충분히 좋은 사람이다", author: "", category: "인생어록" },
  { text: "매일 새로운 나로 태어날 수 있다", author: "", category: "인생어록" },
  { text: "감정도 파도처럼 밀려왔다 빠진다", author: "", category: "인생어록" },
  { text: "용기를 내서 첫 발을 디디어라", author: "", category: "인생어록" },
  { text: "모든 것이 해결되지 않아도 괜찮다", author: "", category: "인생어록" },
  { text: "살아있다는 것 자체가 기적이다", author: "", category: "인생어록" },
  { text: "좋은 일은 천천히 찾아온다", author: "", category: "인생어록" },
  { text: "자신의 심장 소리를 들어라", author: "", category: "인생어록" },
  { text: "삶은 계획대로 되지 않지만 모두 괜찮다", author: "", category: "인생어록" },
  { text: "어제의 실패는 오늘의 교훈이다", author: "", category: "인생어록" },
  { text: "새로운 하루가 또 온다", author: "", category: "인생어록" },
  { text: "당신의 모습 그대로가 아름답다", author: "", category: "인생어록" },
  { text: "고된 날도 지나간다", author: "", category: "인생어록" },
  { text: "이 순간도 언젠가 추억이 될 것이다", author: "", category: "인생어록" },

  // ── 원피스명언 추가 ── [+30개]

  { text: "가슴에 화염을 가진 자가 승리한다", author: "루피", category: "원피스명언" },
  { text: "나의 꿈을 꺾을 수 있는 자는 없다", author: "루피", category: "원피스명언" },
  { text: "고통 없이 변화도 없다", author: "루피", category: "원피스명언" },
  { text: "친구의 꿈을 짓밟으면 안 된다", author: "루피", category: "원피스명언" },
  { text: "왕은 절대 물러서지 않는다", author: "루피", category: "원피스명언" },
  { text: "죽음보다 수치스러운 인생은 없다", author: "조로", category: "원피스명언" },
  { text: "신념을 지키지 못하면 사나이가 아니다", author: "조로", category: "원피스명언" },
  { text: "약한 적과는 싸울 이유도 없다", author: "조로", category: "원피스명언" },
  { text: "강함이란 뭔가를 지키는 것이다", author: "조로", category: "원피스명언" },
  { text: "검객의 길에는 물러남이 없다", author: "조로", category: "원피스명언" },
  { text: "진정한 신사는 약자를 보호한다", author: "상디", category: "원피스명언" },
  { text: "사랑과 열정이 인생의 가치다", author: "상디", category: "원피스명언" },
  { text: "음식 앞에서는 주먹도 내려야 한다", author: "상디", category: "원피스명언" },
  { text: "꿈의 크기는 무한하다", author: "상디", category: "원피스명언" },
  { text: "감사하는 마음을 잃으면 안 된다", author: "나미", category: "원피스명언" },
  { text: "나만의 길을 갈 것이다", author: "나미", category: "원피스명언" },
  { text: "거짓말도 때로는 사람을 살린다", author: "우솝", category: "원피스명언" },
  { text: "용감함은 행동에서 나온다", author: "우솝", category: "원피스명언" },
  { text: "이야기꾼이 되고 싶다", author: "우솝", category: "원피스명언" },
  { text: "역사를 아는 자가 미래를 안다", author: "로빈", category: "원피스명언" },
  { text: "혼자가 아니라는 것이 힘이다", author: "로빈", category: "원피스명언" },
  { text: "배는 우리의 자유다", author: "로빈", category: "원피스명언" },
  { text: "슈퍼는 이 바다의 로망이다", author: "프랑키", category: "원피스명언" },
  { text: "꿈의 배를 지으리라", author: "프랑키", category: "원피스명언" },
  { text: "남자의 낭만은 영원하다", author: "프랑키", category: "원피스명언" },
  { text: "죽음조차도 나를 멈출 수 없다", author: "브룩", category: "원피스명언" },
  { text: "음악이 있으면 어떤 고통도 견딜 수 있다", author: "브룩", category: "원피스명언" },
  { text: "영혼은 죽지 않는다", author: "브룩", category: "원피스명언" },
  { text: "형으로서의 책임을 진다", author: "에이스", category: "원피스명언" },
  { text: "선택의 결과는 자신이 감당한다", author: "에이스", category: "원피스명언" },

  // ── 주식명언 추가 ── [+30개]

  { text: "장기 투자는 인내심의 게임이다", author: "워렌 버핏", category: "주식명언" },
  { text: "투자 성공의 50%는 심리다", author: "워렌 버핏", category: "주식명언" },
  { text: "저가에서 매수하고 고가에서 매도하라", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "기업의 본질을 꿰뚫어야 투자할 수 있다", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "추종자가 아닌 독립적 사고로 투자하라", author: "벤저민 그레이엄", category: "주식명언" },
  { text: "시장의 불황기가 최고의 기회다", author: "피터 린치", category: "주식명언" },
  { text: "근처의 회사에 투자하라", author: "피터 린치", category: "주식명언" },
  { text: "기업 실적 성장이 주가 상승을 만든다", author: "피터 린치", category: "주식명언" },
  { text: "위험한 투자는 고수익을 약속한다", author: "찰리 멍거", category: "주식명언" },
  { text: "경쟁 우위가 있는 회사에 투자하라", author: "찰리 멍거", category: "주식명언" },
  { text: "경제 사이클을 이해하는 것이 중요하다", author: "하워드 막스", category: "주식명언" },
  { text: "과도한 낙관주의를 피하라", author: "하워드 막스", category: "주식명언" },
  { text: "수익성 높은 회사의 주식을 사라", author: "레이 달리오", category: "주식명언" },
  { text: "관계성을 고려한 투자가 핵심이다", author: "레이 달리오", category: "주식명언" },
  { text: "트렌드가 아닌 가치에 투자하라", author: "조지 소로스", category: "주식명언" },
  { text: "모멘텀과 가치의 균형을 잡아라", author: "조지 소로스", category: "주식명언" },
  { text: "반사성이 시장을 좌우한다", author: "조지 소로스", category: "주식명언" },
  { text: "소수 의견이 맞을 때가 많다", author: "앙드레 코스톨라니", category: "주식명언" },
  { text: "주식은 심리 게임이지 수학 게임이 아니다", author: "앙드레 코스톨라니", category: "주식명언" },
  { text: "시장 참여자들의 행동을 관찰하라", author: "앙드레 코스톨라니", category: "주식명언" },
  { text: "기본값으로 돌아가 생각하라", author: "켄 피셔", category: "주식명언" },
  { text: "역사는 반복되지 않지만 운을 한다", author: "켄 피셔", category: "주식명언" },
  { text: "매스 심리의 함정을 피하라", author: "켄 피셔", category: "주식명언" },
  { text: "기업 경영진의 능력을 평가하라", author: "투자 격언", category: "주식명언" },
  { text: "배당금은 투자의 보상이다", author: "투자 격언", category: "주식명언" },
  { text: "손절매는 투자자의 자존심이 아니다", author: "투자 격언", category: "주식명언" },
  { text: "시장은 언제나 소수를 이긴다", author: "투자 격언", category: "주식명언" },
  { text: "작은 포지션부터 시작하라", author: "투자 격언", category: "주식명언" },
  { text: "당신의 원칙을 절대 포기하지 마라", author: "투자 격언", category: "주식명언" },
  { text: "성공한 투자자는 자신의 실패를 숨기지 않는다", author: "투자 격언", category: "주식명언" },

  // ── 외국명언 추가 ── [+25개]

  { text: "문제를 해결하는 능력이 진짜 지혜다", author: "아인슈타인", category: "외국명언" },
  { text: "상상은 지식보다 더 중요하다", author: "아인슈타인", category: "외국명언" },
  { text: "실패 없는 성공은 없다", author: "토마스 에디슨", category: "외국명언" },
  { text: "오늘의 어려움이 내일의 힘이 된다", author: "조지 버나드 쇼", category: "외국명언" },
  { text: "위대한 일은 천천히 완성된다", author: "미켈란젤로", category: "외국명언" },
  { text: "열정이 없으면 위대함도 없다", author: "라파엘", category: "외국명언" },
  { text: "인생은 배움의 연속이다", author: "소크라테스", category: "외국명언" },
  { text: "지금이 최고의 시간이다", author: "아우렐리우스", category: "외국명언" },
  { text: "변화는 모든 성장의 시작이다", author: "하이페티우스", category: "외국명언" },
  { text: "진정한 리더는 봉사자다", author: "일드린", category: "외국명언" },
  { text: "성공은 준비된 자에게만 온다", author: "톰 워트슨", category: "외국명언" },
  { text: "인생의 가치는 영향력이다", author: "존 맥스웰", category: "외국명언" },
  { text: "작은 변화가 큰 결과를 만든다", author: "제임스 클리어", category: "외국명언" },
  { text: "목표 없는 노력은 무가치하다", author: "나이팅게일", category: "외국명언" },
  { text: "마음가짐이 현실을 만든다", author: "조셉 머피", category: "외국명언" },
  { text: "두려움은 거짓 신호일 뿐이다", author: "수잔 제퍼스", category: "외국명언" },
  { text: "행동 없는 말은 공허하다", author: "톰 피터스", category: "외국명언" },
  { text: "멘토를 찾는 것이 성공의 시작이다", author: "짐 론", category: "외국명언" },
  { text: "실패를 경험하지 않은 자는 진정 산 것이 아니다", author: "존 웨인", category: "외국명언" },
  { text: "매일의 선택이 미래를 만든다", author: "스티브 코비", category: "외국명언" },
  { text: "자신을 믿는 것에서 모든 것이 시작된다", author: "오프라 윈프리", category: "외국명언" },
  { text: "관계가 성공의 기반이다", author: "데일 카네기", category: "외국명언" },
  { text: "인내심은 목표를 달성하는 열쇠다", author: "조지 워싱턴", category: "외국명언" },
  { text: "최고에 도달하려면 작은 것부터 시작하라", author: "제임스 해리슨", category: "외국명언" },
  { text: "다른 사람의 기대보다 자신의 꿈을 따르라", author: "스티브 잡스", category: "외국명언" },

  // ── 한국명언 추가 ── [+20개]

  { text: "고향이 그리울 땐 고향을 생각하고 미래가 두려울 땐 꿈을 생각해라", author: "이순신", category: "한국명언" },
  { text: "나라를 위해 목숨을 바치는 것이 진정한 명예다", author: "이순신", category: "한국명언" },
  { text: "절망도 노력으로 극복할 수 있다", author: "류성룡", category: "한국명언" },
  { text: "백성을 먼저 생각하는 것이 통치의 기본이다", author: "세종대왕", category: "한국명언" },
  { text: "학문은 나의 가장 큰 자산이다", author: "최치원", category: "한국명언" },
  { text: "자신의 약점을 아는 것이 성장의 첫걸음이다", author: "황현", category: "한국명언" },
  { text: "정직한 삶이 가장 강한 삶이다", author: "장승업", category: "한국명언" },
  { text: "절제는 모든 미덕의 기초다", author: "이황", category: "한국명언" },
  { text: "독서를 통해 세상을 배울 수 있다", author: "이이", category: "한국명언" },
  { text: "무언의 행동이 말보다 크다", author: "허난설헌", category: "한국명언" },
  { text: "아무리 높은 목표도 작은 시작에서 나온다", author: "윤동주", category: "한국명언" },
  { text: "민족을 위한 희생이 참된 영웅이다", author: "안중근", category: "한국명언" },
  { text: "진리를 추구하는 것이 인생의 목표다", author: "함석헌", category: "한국명언" },
  { text: "겨울을 견디어야 봄을 맞이한다", author: "조운", category: "한국명언" },
  { text: "자유는 책임과 함께 온다", author: "조성환", category: "한국명언" },
  { text: "실패를 두려워하지 않는 것이 성공의 비결이다", author: "박인환", category: "한국명언" },
  { text: "한 번의 열정이 일생을 바꾼다", author: "신라자", category: "한국명언" },
  { text: "올곧은 마음이 사람을 만든다", author: "퇴계 이황", category: "한국명언" },
  { text: "남다른 생각이 남다른 결과를 만든다", author: "전봉준", category: "한국명언" },
  { text: "삶은 계단을 오르는 것이다", author: "한용운", category: "한국명언" },

  // ── 연예인명언 추가 ── [+20개]

  { text: "겉으로의 성공보다 내면의 평온이 중요하다", author: "전지현", category: "연예인명언" },
  { text: "두려움을 피하지 말고 맞서라", author: "정우성", category: "연예인명언" },
  { text: "꾸준함이 어떤 재능도 이긴다", author: "송강호", category: "연예인명언" },
  { text: "자신의 한계를 자꾸만 넘어보라", author: "이병헌", category: "연예인명언" },
  { text: "행복은 다른 곳에 있지 않고 지금 여기에 있다", author: "김해숙", category: "연예인명언" },
  { text: "실패도 좋은 경험이다", author: "류승룡", category: "연예인명언" },
  { text: "작은 것에 감사하는 것이 행복이다", author: "손예진", category: "연예인명언" },
  { text: "내가 할 수 있는 것부터 시작하자", author: "박보검", category: "연예인명언" },
  { text: "자신에게 엄격하고 남에게는 너그러워라", author: "현빈", category: "연예인명언" },
  { text: "변화를 거부하면 성장도 없다", author: "천우희", category: "연예인명언" },
  { text: "노력은 절대 무조건 배신하지 않는다", author: "이정재", category: "연예인명언" },
  { text: "가슴으로 하는 일이 진정한 성공이다", author: "김영철", category: "연예인명언" },
  { text: "겸손해야 배울 수 있다", author: "유아인", category: "연예인명언" },
  { text: "우리는 모두 누군가의 후배고 누군가의 선배다", author: "원빈", category: "연예인명언" },
  { text: "꿈을 이루려면 꿈보다 행동이 중요하다", author: "김수현", category: "연예인명언" },
  { text: "나는 내 삶의 주인공이다", author: "공유", category: "연예인명언" },
  { text: "내 가치는 내가 정한다", author: "이동욱", category: "연예인명언" },
  { text: "마음이 맞으면 모든 것이 가능하다", author: "박신혜", category: "연예인명언" },
  { text: "작은 친절이 큰 행복을 만든다", author: "이민호", category: "연예인명언" },
  { text: "자신의 이야기를 당당하게 말하라", author: "문근영", category: "연예인명언" },

  // ── 인생어록 추가 ── [+20개]

  { text: "가는 말도 고우면 오는 말이 곱다", author: "", category: "인생어록" },
  { text: "나이는 숫자일 뿐이다", author: "", category: "인생어록" },
  { text: "실수는 진행 중인 배움이다", author: "", category: "인생어록" },
  { text: "일관성이 성공을 결정한다", author: "", category: "인생어록" },
  { text: "부정적 생각도 습관이다", author: "", category: "인생어록" },
  { text: "인정과 칭찬은 자유롭다", author: "", category: "인생어록" },
  { text: "삶의 의미는 우리가 만든다", author: "", category: "인생어록" },
  { text: "혼자라는 생각은 착각이다", author: "", category: "인생어록" },
  { text: "오늘의 작은 성공이 내일의 큰 기적이다", author: "", category: "인생어록" },
  { text: "슬픔도 지나고 기쁨도 지나간다", author: "", category: "인생어록" },
  { text: "당신이 원하는 변화가 당신이다", author: "", category: "인생어록" },
  { text: "비교는 행복의 도둑이다", author: "", category: "인생어록" },
  { text: "감정도 날씨처럼 지나간다", author: "", category: "인생어록" },
  { text: "미안하면 할 말이 없다", author: "", category: "인생어록" },
  { text: "고마움을 자주 표현하라", author: "", category: "인생어록" },
  { text: "작은 성공을 축하해주자", author: "", category: "인생어록" },
  { text: "오류도 데이터다", author: "", category: "인생어록" },
  { text: "계획이 뭐든 첫발을 내딛자", author: "", category: "인생어록" },
  { text: "멈추는 것도 한 발전이다", author: "", category: "인생어록" },
  { text: "마지막은 항상 있다는 것을 기억하라", author: "", category: "인생어록" },

  // ── 원피스명언 추가 ── [+10개]

  { text: "나의 보물? 원한다면 주지! 찾아봐! 이 세상의 전부를 거기에 놨으니까!", author: "골드 로저", category: "원피스명언" },
  { text: "친구를 위해 싸우는 게 나약한 거 아니야!", author: "루피", category: "원피스명언" },
  { text: "누군가를 지키기 위해서라면 강해져야 한다!", author: "조로", category: "원피스명언" },
  { text: "내 모든 것을 버릴 수 있어도 꿈은 버릴 수 없어!", author: "루피", category: "원피스명언" },
  { text: "약한 자는 죽고 강한 자가 산다", author: "샹ks", category: "원피스명언" },
  { text: "나는 절대 포기하지 않는다!", author: "루피", category: "원피스명언" },
  { text: "신사는 약한 자를 때리지 않는다", author: "상디", category: "원피스명언" },
  { text: "우리는 이미 죽어 있다", author: "조로", category: "원피스명언" },
  { text: "역사를 움직이는 것은 자유를 원하는 마음이다", author: "로빈", category: "원피스명언" },
  { text: "이 배는 누구에게도 빼앗기지 않는다!", author: "루피", category: "원피스명언" }
];
