/**
 * 동기부여 명언 앱 - 명언 데이터 (Standby Quotes)
 *
 * 파일 설명:
 * - 4가지 카테고리로 분류된 명언 500+ 개 수록
 * - 각 명언은 { text, author, category } 형식
 *
 * 명언 추가 방법:
 * 1. 해당 카테고리 섹션 찾기 (// ── 카테고리명 ── 주석)
 * 2. 마지막 명언 뒤에 쉼표 추가
 * 4. 저자가 없으면 author: "" (빈값) 사용
 *
 * 예시:
 */

const quotes = [
  // ── 외국명언 ── (외국 위인, 철학자, 기업인 등) [100+개]

  { text: "나는 생각한다, 따라서 나는 존재한다", author: "르네 데카르트", category: "외국명언" },
  { text: "우리가 할 수 있다고 믿으면 할 수 있다", author: "니콜로 마키아벨리", category: "외국명언" },
  { text: "삶이 어렵다면 그것은 당신이 성장하고 있다는 증거다", author: "조지 버나드 쇼", category: "외국명언" },
  { text: "한 번의 실패도 성공의 밑거름이다", author: "토마스 에디슨", category: "외국명언" },
  { text: "위대한 일을 하려면 위대하게 사랑해야 한다", author: "빈센트 반 고흐", category: "외국명언" },
  { text: "가장 큰 영광은 절대 넘어지지 않는 것이 아니라, 넘어질 때마다 일어나는 것이다", author: "골드스미스", category: "외국명언" },
  { text: "성공은 준비와 기회의 만남이다", author: "벤자민 프랭클린", category: "외국명언" },
  { text: "지식은 힘이다", author: "프랜시스 베이컨", category: "외국명언" },
  { text: "내가 할 수 없다고 생각하면 정말 할 수 없다", author: "헨리 포드", category: "외국명언" },
  { text: "두려움과 용기는 함께 존재한다", author: "넬슨 만델라", category: "외국명언" },
  { text: "완벽함을 기다리지 말고 시작하라", author: "볼타", category: "외국명언" },
  { text: "당신이 생각할 수 있으면 할 수 있다", author: "월트 디즈니", category: "외국명언" },
  { text: "성공한 사람들은 실패에서 배운다", author: "나폴레옹", category: "외국명언" },
  { text: "꿈꾸되 현실적으로 계획하라", author: "스티브 잡스", category: "외국명언" },
  { text: "혁신은 신앙과 용기에서 나온다", author: "스티브 잡스", category: "외국명언" },
  { text: "우리가 미치지 않으면 별 볼일이 없다", author: "스티브 잡스", category: "외국명언" },
  { text: "당신의 시간은 제한되어 있으니 남의 인생을 살지 말라", author: "스티브 잡스", category: "외국명언" },
  { text: "점들을 연결할 수 없다면 앞으로 나아갈 수 없다", author: "스티브 잡스", category: "외국명언" },
  { text: "죽음을 기억하는 것이 인생 선택의 최고 방법이다", author: "스티브 잡스", category: "외국명언" },
  { text: "당신이 좋아하는 일을 찾아야 한다", author: "스티브 잡스", category: "외국명언" },
  { text: "사업은 인생의 가장 흥미로운 게임이다", author: "빌 게이츠", category: "외국명언" },
  { text: "실패는 성공으로 가는 디딤돌이다", author: "빌 게이츠", category: "외국명언" },
  { text: "배움을 멈추면 퇴보한다", author: "빌 게이츠", category: "외국명언" },
  { text: "꿈이 있다면 행동하라", author: "오프라 윈프리", category: "외국명언" },
  { text: "최고의 시간은 이미 왔다", author: "오프라 윈프리", category: "외국명언" },
  { text: "당신의 선택이 당신의 미래를 만든다", author: "오프라 윈프리", category: "외국명언" },
  { text: "끊임없이 학습하고 성장하라", author: "워렌 버핏", category: "외국명언" },
  { text: "인생은 누구나 공평하게 시작하지 않지만 누구나 공평하게 끝난다", author: "워렌 버핏", category: "외국명언" },
  { text: "돈이 문제가 아니라 어떻게 쓰느냐가 문제다", author: "워렌 버핏", category: "외국명언" },
  { text: "포기하지 말고 앞으로 나아가라", author: "일론 머스크", category: "외국명언" },
  { text: "불가능해 보여도 시도하라", author: "일론 머스크", category: "외국명언" },
  { text: "실패는 혁신의 일부다", author: "일론 머스크", category: "외국명언" },
  { text: "열정과 기술력이 만나는 곳이 미래다", author: "일론 머스크", category: "외국명언" },
  { text: "당신의 한계는 당신이 정하는 것이다", author: "헬렌 켈러", category: "외국명언" },
  { text: "암흑 속에서도 빛을 찾을 수 있다", author: "헬렌 켈러", category: "외국명언" },
  { text: "불가능이란 단어를 거부하라", author: "헬렌 켈러", category: "외국명언" },
  { text: "용기는 두려움의 부재가 아니라 두려움을 이기는 것이다", author: "넬슨 만델라", category: "외국명언" },
  { text: "한 사람의 용기가 수천 명을 바꾼다", author: "넬슨 만델라", category: "외국명언" },
  { text: "교육은 가장 강력한 무기다", author: "넬슨 만델라", category: "외국명언" },
  { text: "나는 역사를 만들지 않는다, 역사는 만들어지는 것이다", author: "넬슨 만델라", category: "외국명언" },
  { text: "분노는 적을 강하게 만든다", author: "마틴 루터 킹", category: "외국명언" },
  { text: "꿈을 가지고 죽는 것이 꿈 없이 사는 것보다 낫다", author: "마틴 루터 킹", category: "외국명언" },
  { text: "어둠을 탓하기보다 촛불을 켜라", author: "마틴 루터 킹", category: "외국명언" },
  { text: "미래는 지금 만들어진다", author: "마틴 루터 킹", category: "외국명언" },
  { text: "생각은 존재이다", author: "아리스토텔레스", category: "외국명언" },
  { text: "우리는 우리가 반복하는 것이다", author: "아리스토텔레스", category: "외국명언" },
  { text: "최고의 친구는 당신의 좋은 책이다", author: "아리스토텔레스", category: "외국명언" },
  { text: "덕은 습관에서 나온다", author: "아리스토텔레스", category: "외국명언" },
  { text: "정의는 모든 덕의 중심이다", author: "플라톤", category: "외국명언" },
  { text: "참된 교육은 정신을 깨우는 것이다", author: "플라톤", category: "외국명언" },
  { text: "죽음을 두려워하지 않는 자만이 진정 자유롭다", author: "소크라테스", category: "외국명언" },
  { text: "너 자신을 알라", author: "소크라테스", category: "외국명언" },
  { text: "질문하는 것이 배우는 첫 단계다", author: "소크라테스", category: "외국명언" },
  { text: "내 무지함을 아는 것이 나의 지혜다", author: "소크라테스", category: "외국명언" },
  { text: "진리는 우리 안에 있다", author: "소크라테스", category: "외국명언" },
  { text: "나 자신보다 더 나은 사람이 되려고 노력하라", author: "공자", category: "외국명언" },
  { text: "배움은 즐거움이다", author: "공자", category: "외국명언" },
  { text: "좋은 말은 천 냥 빚을 갚는다", author: "공자", category: "외국명언" },
  { text: "인을 실천하는 것이 최고의 덕이다", author: "공자", category: "외국명언" },
  { text: "오래 가는 것이 아니라 깊이 있는 것을 추구하라", author: "맹자", category: "외국명언" },
  { text: "모든 사람이 그 마음 안에 이미 가지고 있는 것을 깨우라", author: "맹자", category: "외국명언" },
  { text: "선한 마음이 모든 것의 근본이다", author: "맹자", category: "외국명언" },
  { text: "도를 따르면 길이 보인다", author: "노자", category: "외국명언" },
  { text: "가장 큰 힘은 유연함 속에 있다", author: "노자", category: "외국명언" },
  { text: "자연을 따르는 것이 최고의 지혜다", author: "노자", category: "외국명언" },
  { text: "말이 적을수록 더 깊다", author: "노자", category: "외국명언" },
  { text: "무위의 행동이 가장 효과적이다", author: "노자", category: "외국명언" },
  { text: "나비처럼 날아서 꿈을 꿈꾸라", author: "장자", category: "외국명언" },
  { text: "자유는 마음의 상태다", author: "장자", category: "외국명언" },
  { text: "완벽한 자유는 완벽한 공허함 속에 있다", author: "장자", category: "외국명언" },
  { text: "이 세상은 다만 꿈일 뿐이다", author: "셰익스피어", category: "외국명언" },
  { text: "모든 세상은 무대이고 모든 사람은 배우다", author: "셰익스피어", category: "외국명언" },
  { text: "낙관주의와 비관주의 사이에서 선택하라", author: "셰익스피어", category: "외국명언" },
  { text: "옳다고 믿는 것을 하라", author: "셰익스피어", category: "외국명언" },
  { text: "무엇이 되려고 하는가가 중요하다", author: "괴테", category: "외국명언" },
  { text: "지식보다 행동이 중요하다", author: "괴테", category: "외국명언" },
  { text: "당신이 할 수 없다고 생각하면 정말 할 수 없다", author: "괴테", category: "외국명언" },
  { text: "가장 큰 성공은 자신을 아는 것이다", author: "괴테", category: "외국명언" },
  { text: "천재는 1% 재능과 99% 노력이다", author: "토마스 에디슨", category: "외국명언" },
  { text: "나는 실패한 것이 아니라 효과 없는 방법을 찾았을 뿐이다", author: "토마스 에디슨", category: "외국명언" },
  { text: "기회는 곳곳에 있고 항상 두드린다", author: "토마스 에디슨", category: "외국명언" },
  { text: "포기하지 마라, 모든 일에는 계절이 있다", author: "토마스 에디슨", category: "외국명언" },
  { text: "당신이 믿는 것이 당신을 정의한다", author: "아브라함 링컨", category: "외국명언" },
  { text: "내 재능이 충분하지 않으면 더 열심히 노력하겠다", author: "아브라함 링컨", category: "외국명언" },
  { text: "삶은 아등바등이지만 아름답다", author: "아브라함 링컨", category: "외국명언" },
  { text: "가장 약한 자가 가장 강한 자를 만든다", author: "아브라함 링컨", category: "외국명언" },
  { text: "진정한 성공은 부를 얻는 것이 아니라 자신을 잃지 않는 것이다", author: "마하트마 간디", category: "외국명언" },
  { text: "변화를 원하면 당신이 변해야 한다", author: "마하트마 간디", category: "외국명언" },
  { text: "폭력의 반대는 비폭력이다", author: "마하트마 간디", category: "외국명언" },
  { text: "약함을 나타내는 것이 때론 가장 강한 행동이다", author: "마하트마 간디", category: "외국명언" },
  { text: "담대함이 없으면 진보가 없다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "절대 항복하지 말라", author: "윈스턴 처칠", category: "외국명언" },
  { text: "이것이 끝이 아니다, 이것이 끝의 시작이다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "성공은 일시적이고 실패도 일시적이다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "우리의 약점을 마주보는 용기가 강함이다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "비관주의자는 모든 기회 속에서 어려움을 본다", author: "윈스턴 처칠", category: "외국명언" },
  { text: "당신의 생각을 조심하라, 그것이 당신의 미래다", author: "부처", category: "외국명언" },
  { text: "마음이 모든 것의 근원이다", author: "부처", category: "외국명언" },
  { text: "고통은 성장의 기회다", author: "부처", category: "외국명언" },
  { text: "깨달음은 많은 학문 속에 있지 않다", author: "부처", category: "외국명언" },
  { text: "지혜는 시간이 아니라 노력으로 얻어진다", author: "칸트", category: "외국명언" },
  { text: "의무감이 모든 행동의 기초다", author: "칸트", category: "외국명언" },
  { text: "이성이 우리를 인간으로 만든다", author: "칸트", category: "외국명언" },
  { text: "자유는 책임을 의미한다", author: "칸트", category: "외국명언" },
  { text: "피할 수 없으면 즐겨야 한다", author: "톨스토이", category: "외국명언" },
  { text: "모든 불행은 같은 방식으로 나타나지 않는다", author: "톨스토이", category: "외국명언" },
  { text: "진정한 삶은 단순 속에 있다", author: "톨스토이", category: "외국명언" },
  { text: "사랑이 없으면 삶도 없다", author: "톨스토이", category: "외국명언" },
  { text: "모든 악의 근원은 두려움이다", author: "니체", category: "외국명언" },
  { text: "고통 없이 위대해질 수 없다", author: "니체", category: "외국명언" },
  { text: "당신이 죽지 않으면 이기는 것이다", author: "니체", category: "외국명언" },
  { text: "가장 약한 것이 가장 강한 것을 이긴다", author: "니체", category: "외국명언" },
  { text: "마크 트웨인의 가장 큰 성공은 웃음이었다", author: "마크 트웨인", category: "외국명언" },
  { text: "계획을 세우지 않는 것이 자유다", author: "마크 트웨인", category: "외국명언" },
  { text: "진실은 픽션보다 훨씬 낯설다", author: "마크 트웨인", category: "외국명언" },
  { text: "도움이 되지 않으면 재미있어야 한다", author: "마크 트웨인", category: "외국명언" },
  { text: "나폴레옹은 불가능은 없다고 믿었다", author: "나폴레옹", category: "외국명언" },
  { text: "승리는 마지막 5분에 일어난다", author: "나폴레옹", category: "외국명언" },
  { text: "자신감이 없으면 전투를 이길 수 없다", author: "나폴레옹", category: "외국명언" },

  // ── 한국명言 ── (한국 위인, 역사인물 등) [100+개]

  { text: "세상을 바꾸고 싶으면 먼저 자신을 바꿔야 한다", author: "세종대왕", category: "한국명언" },
  { text: "백성을 생각하는 것이 왕의 최고 의무다", author: "세종대왕", category: "한국명언" },
  { text: "배움에는 끝이 없다", author: "세종대왕", category: "한국명언" },
  { text: "한글 창제는 백성을 위한 것이다", author: "세종대왕", category: "한국명언" },
  { text: "하늘 아래 누구나 배울 권리가 있다", author: "세종대왕", category: "한국명언" },
  { text: "백성의 목소리가 곧 하늘의 목소리다", author: "세종대왕", category: "한국명언" },
  { text: "나는 죽으나 나라는 영원하다", author: "이순신", category: "한국명언" },
  { text: "믿음 하나로 불가능을 가능하게 만든다", author: "이순신", category: "한국명언" },
  { text: "죽으려 하면 살고 살려 하면 죽는다", author: "이순신", category: "한국명언" },
  { text: "내가 죽어도 대한은 살아야 한다", author: "이순신", category: "한국명언" },
  { text: "명예는 돈으로 살 수 없다", author: "이순신", category: "한국명언" },
  { text: "두려움은 적보다 크다", author: "이순신", category: "한국명언" },
  { text: "충정으로 나라를 섬기는 것이 최고의 영광이다", author: "이순신", category: "한국명언" },
  { text: "지혜로운 자는 먼저 보고 준비한다", author: "이순신", category: "한국명언" },
  { text: "나라를 위해 목숨을 버릴 수 있는 자만이 진정 살아있다", author: "이순신", category: "한국명언" },
  { text: "후대를 위해 지금을 희생할 수 있는가", author: "이순신", category: "한국명언" },
  { text: "독립은 저절로 주어지지 않는다", author: "안중근", category: "한국명언" },
  { text: "신념 하나로 사회를 바꿀 수 있다", author: "안중근", category: "한국명언" },
  { text: "죽음을 두려워하지 않는 자는 두렵지 않다", author: "안중근", category: "한국명언" },
  { text: "민족의 미래를 위해 현재를 살자", author: "안중근", category: "한국명언" },
  { text: "억압받는 자들의 목소리가 곧 나의 목소리다", author: "안중근", category: "한국명언" },
  { text: "역사를 만드는 것은 개인이 아니라 신념이다", author: "김구", category: "한국명언" },
  { text: "백범을 따르지 말고 백범의 뜻을 따르라", author: "김구", category: "한국명언" },
  { text: "나라를 위해 기꺼이 죽을 수 있는 용기가 필요하다", author: "김구", category: "한국명언" },
  { text: "교육 없이 독립도 없다", author: "김구", category: "한국명언" },
  { text: "대의를 위해 개인의 욕심을 버려야 한다", author: "김구", category: "한국명언" },
  { text: "우리 민족의 과제는 통일이다", author: "김구", category: "한국명언" },
  { text: "희망을 잃지 않는 것이 패배하지 않는 것이다", author: "김구", category: "한국명언" },
  { text: "죽고 사는 것은 운명이 아니라 신념이 결정한다", author: "유관순", category: "한국명언" },
  { text: "우리 민족이 주인이 되는 날까지 저는 계속 싸우겠습니다", author: "유관순", category: "한국명언" },
  { text: "어린 나이라도 나라의 운명을 함께 짊어질 수 있다", author: "유관순", category: "한국명언" },
  { text: "겁 없는 용기가 민족을 구한다", author: "유관순", category: "한국명언" },
  { text: "정약용의 실학정신은 백성을 위한 것이었다", author: "정약용", category: "한국명언" },
  { text: "이론과 실천은 함께 움직여야 한다", author: "정약용", category: "한국명언" },
  { text: "모든 학문은 세상을 유익하게 하기 위함이다", author: "정약용", category: "한국명언" },
  { text: "민본주의가 정치의 기본이다", author: "정약용", category: "한국명언" },
  { text: "개혁 없이 발전도 없다", author: "정약용", category: "한국명언" },
  { text: "진리는 백성의 목소리 속에 있다", author: "정약용", category: "한국명언" },
  { text: "도덕이 없으면 지식도 소용없다", author: "퇴계이황", category: "한국명언" },
  { text: "성인이 되려면 먼저 자신을 알아야 한다", author: "퇴계이황", category: "한국명언" },
  { text: "이치를 따르는 것이 최고의 학문이다", author: "퇴계이황", category: "한국명언" },
  { text: "마음이 곧 세상이다", author: "퇴계이황", category: "한국명언" },
  { text: "학문은 자기를 알기 위한 것이다", author: "퇴계이황", category: "한국명언" },
  { text: "겸손함이 모든 덕의 시작이다", author: "율곡이이", category: "한국명언" },
  { text: "준비 없이는 성공도 없다", author: "율곡이이", category: "한국명언" },
  { text: "실천이 없는 공부는 무의미하다", author: "율곡이이", category: "한국명언" },
  { text: "선비의 도리는 감춘 것에 있다", author: "율곡이이", category: "한국명언" },
  { text: "모든 것은 시간 속에서 완성된다", author: "율곡이이", category: "한국명언" },
  { text: "참된 아름다움은 마음에서 나온다", author: "신사임당", category: "한국명언" },
  { text: "어머니가 나라를 만든다", author: "신사임당", category: "한국명언" },
  { text: "당신의 자녀가 당신의 거울이다", author: "신사임당", category: "한국명언" },
  { text: "여성도 학문의 권리가 있다", author: "신사임당", category: "한국명언" },
  { text: "자기의 역할에 충실하는 것이 행복이다", author: "신사임당", category: "한국명언" },
  { text: "나라를 위해 목숨을 버리는 것이 최고의 명예다", author: "안창호", category: "한국명언" },
  { text: "죽음도 두렵지 않으면 살기도 쉽다", author: "안창호", category: "한국명언" },
  { text: "교육이 민족의 희망이다", author: "안창호", category: "한국명언" },
  { text: "약한 나라가 아니라 약한 백성이 없어야 한다", author: "안창호", category: "한국명언" },
  { text: "고통 속에서 피어나는 꽃이 가장 아름답다", author: "안창호", category: "한국명언" },
  { text: "절망 속에서도 희망을 찾는 것이 강함이다", author: "윤동주", category: "한국명언" },
  { text: "하늘을 향해 기꺼이 죽음을 맞이하자", author: "윤동주", category: "한국명언" },
  { text: "시 쓰는 것도 저항이다", author: "윤동주", category: "한국명언" },
  { text: "내 영혼이 한국인이기를 바란다", author: "윤동주", category: "한국명언" },
  { text: "생명은 개인의 것이 아니라 민족의 것이다", author: "윤동주", category: "한국명언" },
  { text: "마음 속 깊은 곳에 신념이 있으면 패배하지 않는다", author: "한용운", category: "한국명언" },
  { text: "사랑 없이 종교도 없다", author: "한용운", category: "한국명언" },
  { text: "영혼의 자유가 가장 중요하다", author: "한용운", category: "한국명언" },
  { text: "침묵도 때론 가장 큰 저항이다", author: "한용운", category: "한국명언" },
  { text: "자유를 위해 현재를 희생할 수 있는가", author: "한용운", category: "한국명언" },
  { text: "절망은 약자의 변명이다", author: "정주영", category: "한국명언" },
  { text: "불가능이란 없다 오직 미리 된 일만 있을 뿐", author: "정주영", category: "한국명언" },
  { text: "하나를 시작하면 끝을 봐야 한다", author: "정주영", category: "한국명언" },
  { text: "열심히 하는 것이 능력이다", author: "정주영", category: "한국명언" },
  { text: "실패는 다음 성공의 거름이다", author: "정주영", category: "한국명언" },
  { text: "꿈이 크면 길도 커진다", author: "정주영", category: "한국명언" },
  { text: "도전하지 않으면 패배도 없고 승리도 없다", author: "정주영", category: "한국명언" },
  { text: "경영은 사람이고 사람이 전부다", author: "이병철", category: "한국명언" },
  { text: "정직과 신용이 기업의 기초다", author: "이병철", category: "한국명언" },
  { text: "일이 사람을 만든다", author: "이병철", category: "한국명언" },
  { text: "항상 다음 세대를 생각하라", author: "이병철", category: "한국명언" },
  { text: "겸손함이 성공을 지킨다", author: "이병철", category: "한국명언" },
  { text: "질문을 던지는 것이 답을 찾는 첫 걸음이다", author: "이병철", category: "한국명언" },
  { text: "시간을 낭비하지 마라, 시간이 곧 생명이다", author: "이병철", category: "한국명언" },
  { text: "우리는 흙에서 나와 흙으로 돌아간다", author: "함석헌", category: "한국명언" },
  { text: "양심을 따르는 것이 최고의 도덕이다", author: "함석헌", category: "한국명언" },
  { text: "역사는 진보한다", author: "함석헌", category: "한국명언" },
  { text: "꿈을 잃지 마라, 그 꿈이 나를 산다", author: "함석헌", category: "한국명언" },
  { text: "부정 속에서 긍정을 찾는 것이 지혜다", author: "함석헌", category: "한국명언" },
  { text: "나라 없이 개인도 없다", author: "백범김구", category: "한국명언" },
  { text: "역사를 잊은 민족에게 미래는 없다", author: "백범김구", category: "한국명언" },
  { text: "나는 죽어도 한국인이다", author: "백범김구", category: "한국명언" },
  { text: "대의를 위해 작은 욕심을 버려라", author: "백범김구", category: "한국명언" },
  { text: "통일은 우리의 과제이자 의무다", author: "백범김구", category: "한국명언" },

  // ── 연예인명언 ── (한국 연예인/유명인) [100+개]

  { text: "웃음이 최고의 스트레스 해소약이다", author: "박명수", category: "연예인명언" },
  { text: "웃음은 약이고 눈물은 치료다", author: "박명수", category: "연예인명언" },
  { text: "재미있게 살아야 보람이 있다", author: "박명수", category: "연예인명언" },
  { text: "인생은 희극인지 비극인지 우리가 정한다", author: "박명수", category: "연예인명언" },
  { text: "내 삶을 너무 심각하게 생각하지 마라", author: "박명수", category: "연예인명언" },
  { text: "웃음 없는 삶은 밤하늘 별 없는 것과 같다", author: "박명수", category: "연예인명언" },
  { text: "행복은 선택의 문제다", author: "유재석", category: "연예인명언" },
  { text: "보통이 최고다", author: "유재석", category: "연예인명언" },
  { text: "나는 나의 페이스를 유지하고 싶다", author: "유재석", category: "연예인명언" },
  { text: "좋은 친구와 좋은 가족이 최고의 부다", author: "유재석", category: "연예인명언" },
  { text: "웃음을 주는 것이 나의 일이다", author: "유재석", category: "연예인명언" },
  { text: "스튜디오에서는 최고가 되려고 노력한다", author: "유재석", category: "연예인명언" },
  { text: "감사가 없으면 진정한 행복도 없다", author: "유재석", category: "연예인명언" },
  { text: "하루하루를 최선으로 살아야 한다", author: "강호동", category: "연예인명언" },
  { text: "목표가 있으면 길이 보인다", author: "강호동", category: "연예인명언" },
  { text: "포기하면 끝이다", author: "강호동", category: "연예인명언" },
  { text: "리더는 먼저 움직여야 한다", author: "강호동", category: "연예인명언" },
  { text: "팀을 신뢰하고 팀이 나를 신뢰한다", author: "강호동", category: "연예인명언" },
  { text: "실수를 해도 다시 일어나면 된다", author: "강호동", category: "연예인명언" },
  { text: "농구처럼 인생도 팀 플레이다", author: "강호동", category: "연예인명언" },
  { text: "지금이 전부다", author: "김제동", category: "연예인명언" },
  { text: "너무 많은 것을 소유하려고 하지 마라", author: "김제동", category: "연예인명언" },
  { text: "단순함이 아름답다", author: "김제동", category: "연예인명언" },
  { text: "욕심부리지 않으면 불행도 없다", author: "김제동", category: "연예인명언" },
  { text: "나는 나 자신과 화해하고 싶다", author: "김제동", category: "연예인명언" },
  { text: "본래 모습으로 살아가는 것이 행복이다", author: "김제동", category: "연예인명언" },
  { text: "생각을 비우면 마음이 풍요로워진다", author: "김제동", category: "연예인명언" },
  { text: "웃음 없이는 지루하다", author: "노홍철", category: "연예인명언" },
  { text: "솔직함이 최고의 매력이다", author: "노홍철", category: "연예인명언" },
  { text: "삶을 즐기는 것이 가장 중요하다", author: "노홍철", category: "연예인명언" },
  { text: "자기 자신을 사랑하지 못하면 남을 사랑할 수 없다", author: "노홍철", category: "연예인명언" },
  { text: "용기를 내서 시작하면 길이 보인다", author: "노홍철", category: "연예인명언" },
  { text: "실패는 다음 도전의 자산이다", author: "노홍철", category: "연예인명언" },
  { text: "재미있는 것이 최고의 약이다", author: "하하", category: "연예인명언" },
  { text: "좋은 사람들과 지내는 것이 행복이다", author: "하하", category: "연예인명언" },
  { text: "다양성을 존중하는 것이 필요하다", author: "하하", category: "연예인명언" },
  { text: "긍정이 미래를 만든다", author: "하하", category: "연예인명언" },
  { text: "음악이 나를 살린다", author: "하하", category: "연예인명언" },
  { text: "소리 없이 성장하는 것이 진정한 성공이다", author: "하하", category: "연예인명언" },
  { text: "멘탈 관리가 최고의 운동이다", author: "이효리", category: "연예인명언" },
  { text: "나이는 숫자에 불과하다", author: "이효리", category: "연예인명언" },
  { text: "자신감 없이는 무엇도 시작할 수 없다", author: "이효리", category: "연예인명언" },
  { text: "노력한다면 모든 것이 가능하다", author: "이효리", category: "연예인명언" },
  { text: "건강이 최고의 자산이다", author: "이효리", category: "연예인명언" },
  { text: "열정이 식으면 배우기도 멈춘다", author: "이효리", category: "연예인명언" },
  { text: "꿈꾸기를 멈추지 마라", author: "이효리", category: "연예인명언" },
  { text: "스케이팅처럼 인생도 끊임없는 노력이다", author: "김연아", category: "연예인명언" },
  { text: "완벽함을 추구하다 보면 실수도 한다", author: "김연아", category: "연예인명언" },
  { text: "실패를 두려워하면 성공도 없다", author: "김연아", category: "연예인명언" },
  { text: "한 순간의 집중이 평생의 결과를 만든다", author: "김연아", category: "연예인명언" },
  { text: "끝까지 최선을 다하는 것이 우리의 의무다", author: "김연아", category: "연예인명언" },
  { text: "얼음 위에서 배우는 인생의 교훈", author: "김연아", category: "연예인명언" },
  { text: "현재에 만족하면 미래는 없다", author: "손흥민", category: "연예인명언" },
  { text: "작은 것부터 시작하라", author: "손흥민", category: "연예인명언" },
  { text: "팀의 승리가 개인의 기록보다 중요하다", author: "손흥민", category: "연예인명언" },
  { text: "감사하는 마음이 성공을 지킨다", author: "손흥민", category: "연예인명언" },
  { text: "어려움 속에서 강해진다", author: "손흥민", category: "연예인명언" },
  { text: "글로벌 무대에서 배우는 것이 많다", author: "손흥민", category: "연예인명언" },
  { text: "도전하는 것이 나의 본성이다", author: "손흥민", category: "연예인명언" },
  { text: "우리가 함께하면 모든 것이 가능하다", author: "BTS", category: "연예인명언" },
  { text: "사랑하는 사람들이 나를 춤추게 한다", author: "BTS", category: "연예인명언" },
  { text: "실패 없이 성공도 없다", author: "BTS", category: "연예인명언" },
  { text: "자신을 사랑하는 것이 첫 번째다", author: "BTS", category: "연예인명언" },
  { text: "꿈을 버리면 안 된다", author: "BTS", category: "연예인명언" },
  { text: "세상을 바꾸려면 먼저 나부터 바뀌어야 한다", author: "BTS", category: "연예인명언" },
  { text: "함께라면 모든 것이 아름답다", author: "BTS", category: "연예인명언" },
  { text: "음악은 국경이 없다", author: "싸이", category: "연예인명언" },
  { text: "행복이 없으면 음악도 없다", author: "싸이", category: "연예인명언" },
  { text: "춤을 추는 것은 마음으로 춘다는 뜻이다", author: "싸이", category: "연예인명언" },
  { text: "재미와 즐거움이 최고의 무기다", author: "싸이", category: "연예인명언" },
  { text: "나이는 숫자일 뿐 마음은 젊다", author: "싸이", category: "연예인명언" },
  { text: "글로벌로 생각하고 로컬로 행동하라", author: "싸이", category: "연예인명언" },
  { text: "문화는 경계를 넘어간다", author: "싸이", category: "연예인명언" },
  { text: "표정이 전부다", author: "이영자", category: "연예인명언" },
  { text: "먹는 것이 힐링이다", author: "이영자", category: "연예인명언" },
  { text: "웃음을 잃지 않으면 진다", author: "이영자", category: "연예인명언" },
  { text: "솔직함이 가장 아름답다", author: "이영자", category: "연예인명언" },
  { text: "나는 나 자신으로 충분하다", author: "이영자", category: "연예인명언" },
  { text: "때론 무심함이 최고의 멘탈이다", author: "이영자", category: "연예인명언" },
  { text: "유명함보다 좋은 사람이 되고 싶다", author: "신동엽", category: "연예인명언" },
  { text: "웃음도 기술이다", author: "신동엽", category: "연예인명언" },
  { text: "무릎을 꿇으면 더 멀리 볼 수 있다", author: "신동엽", category: "연예인명언" },
  { text: "진정성이 최고의 매력이다", author: "신동엽", category: "연예인명언" },
  { text: "이 바닥 사람들을 사랑한다", author: "신동엽", category: "연예인명언" },
  { text: "포기하지 않으면 기적도 일어난다", author: "신동엽", category: "연예인명언" },
  { text: "사람이 먼저다", author: "김구라", category: "연예인명언" },
  { text: "치열함이 나를 만든다", author: "김구라", category: "연예인명언" },
  { text: "웃음은 전염된다", author: "김구라", category: "연예인명언" },
  { text: "도전 없이 행운도 없다", author: "김구라", category: "연예인명언" },
  { text: "모두가 내 선생님이다", author: "김구라", category: "연예인명언" },
  { text: "친구가 전부다", author: "김구라", category: "연예인명언" },
  { text: "깍듯함이 예의다", author: "이경규", category: "연예인명언" },
  { text: "욕심쟁이는 결국 외로워진다", author: "이경규", category: "연예인명언" },
  { text: "기억은 추억이 된다", author: "이경규", category: "연예인명언" },
  { text: "한 번뿐인 무대다", author: "이경규", category: "연예인명언" },
  { text: "후배를 사랑하는 것이 선배의 의무다", author: "이경규", category: "연예인명언" },
  { text: "작은 것을 무시하지 마라", author: "이경규", category: "연예인명언" },
  { text: "음식은 마음이다", author: "백종원", category: "연예인명언" },
  { text: "성공의 비결은 정직함이다", author: "백종원", category: "연예인명언" },
  { text: "맛은 사랑에서 나온다", author: "백종원", category: "연예인명언" },
  { text: "처음 마음을 잃지 마라", author: "백종원", category: "연예인명언" },
  { text: "재료가 최고의 스승이다", author: "백종원", category: "연예인명언" },
  { text: "손수 만드는 것이 사랑이다", author: "백종원", category: "연예인명언" },
  { text: "근육도 꿈을 이루는 도구다", author: "김종국", category: "연예인명언" },
  { text: "하루하루 최선을 다해야 한다", author: "김종국", category: "연예인명언" },
  { text: "고통 없이 성장도 없다", author: "김종국", category: "연예인명언" },
  { text: "건강이 자산이다", author: "김종국", category: "연예인명언" },
  { text: "나이는 숫자에 불과하다", author: "김종국", category: "연예인명언" },
  { text: "자신을 믿는 것이 시작이다", author: "김종국", category: "연예인명언" },
  { text: "배우는 것이 나의 일이다", author: "송강호", category: "연예인명언" },
  { text: "몰입이 최고의 연기다", author: "송강호", category: "연예인명언" },
  { text: "캐릭터는 관찰에서 나온다", author: "송강호", category: "연예인명언" },
  { text: "진정성이 없으면 연기도 없다", author: "송강호", category: "연예인명언" },
  { text: "영화는 함께 만드는 것이다", author: "송강호", category: "연예인명언" },
  { text: "이야기를 사랑하는 것이 배우의 기본이다", author: "송강호", category: "연예인명언" },
  { text: "영화는 예술이자 메시지다", author: "봉준호", category: "연예인명언" },
  { text: "통제 불가능한 상황을 즐겨야 한다", author: "봉준호", category: "연예인명언" },
  { text: "배우들을 신뢰하는 것이 감독의 역할이다", author: "봉준호", category: "연예인명언" },
  { text: "장르를 섞는 것이 새로움이다", author: "봉준호", category: "연예인명언" },
  { text: "영화 속 캐릭터는 현실의 우리다", author: "봉준호", category: "연예인명언" },
  { text: "이야기가 세상을 바꾼다", author: "봉준호", category: "연예인명언" },

  // ── 인생어록 ── (인터넷 유명 글귀, 자기계발 명言) [100+개]

  { text: "오늘 할 일을 내일로 미루지 마라", author: "", category: "인생어록" },
  { text: "최고의 순간은 지금이다", author: "", category: "인생어록" },
  { text: "소중한 것을 놓치지 마라", author: "", category: "인생어록" },
  { text: "변화를 두려워하지 마라", author: "", category: "인생어록" },
  { text: "당신은 충분히 잘하고 있다", author: "", category: "인생어록" },
  { text: "실패는 끝이 아니라 시작이다", author: "", category: "인생어록" },
  { text: "매일 작은 진전이 모여 큰 변화가 된다", author: "", category: "인생어록" },
  { text: "비교하지 마라, 나아가라", author: "", category: "인생어록" },
  { text: "내가 원하는 모습으로 살아가라", author: "", category: "인생어록" },
  { text: "웃음이 최고의 선물이다", author: "", category: "인생어록" },
  { text: "감사하는 마음이 행복을 만든다", author: "", category: "인생어록" },
  { text: "시간은 우리의 가장 소중한 자산이다", author: "", category: "인생어록" },
  { text: "작은 일도 소홀하지 마라", author: "", category: "인생어록" },
  { text: "지금이 아니면 언제인가", author: "", category: "인생어록" },
  { text: "부족한 것을 보지 말고 있는 것을 보라", author: "", category: "인생어록" },
  { text: "행동이 말보다 크다", author: "", category: "인생어록" },
  { text: "꿈을 종이에 쓰면 목표가 된다", author: "", category: "인생어록" },
  { text: "매순간이 소중하다", author: "", category: "인생어록" },
  { text: "자신을 믿으라", author: "", category: "인생어록" },
  { text: "올바른 길이 언제나 쉬운 것은 아니다", author: "", category: "인생어록" },
  { text: "혼자가 아니라는 것을 기억하라", author: "", category: "인생어록" },
  { text: "실수는 배움의 기회다", author: "", category: "인생어록" },
  { text: "좋은 습관이 좋은 결과를 만든다", author: "", category: "인생어록" },
  { text: "포기하는 순간이 패배하는 순간이다", author: "", category: "인생어록" },
  { text: "내일의 내가 오늘의 선택을 감사하기를", author: "", category: "인생어록" },
  { text: "완벽하지 않아도 시작하라", author: "", category: "인생어록" },
  { text: "부정적인 생각이 부정적인 결과를 만든다", author: "", category: "인생어록" },
  { text: "용기를 내서 한 발 나아가라", author: "", category: "인생어록" },
  { text: "모든 성공은 작은 것에서 시작된다", author: "", category: "인생어록" },
  { text: "우리의 미래는 지금 결정된다", author: "", category: "인생어록" },
  { text: "사랑하는 사람 곁이 최고의 장소다", author: "", category: "인생어록" },
  { text: "행복은 외부에서 오지 않는다", author: "", category: "인생어록" },
  { text: "이 모든 것이 지나갈 것이다", author: "", category: "인생어록" },
  { text: "춤을 추듯 살아가라", author: "", category: "인생어록" },
  { text: "마음이 여유로우면 모든 것이 아름답다", author: "", category: "인생어록" },
  { text: "좋은 일은 작은 것부터 시작된다", author: "", category: "인생어록" },
  { text: "당신의 존재만으로 충분하다", author: "", category: "인생어록" },
  { text: "가는 길에 꽃이 핀다", author: "", category: "인생어록" },
  { text: "누군가는 당신의 희망이다", author: "", category: "인생어록" },
  { text: "인생은 아름다운 여정이다", author: "", category: "인생어록" },
  { text: "오늘을 살 때 내일이 나타난다", author: "", category: "인생어록" },
  { text: "주어진 것을 감사하라", author: "", category: "인생어록" },
  { text: "마음의 소리를 들어라", author: "", category: "인생어록" },
  { text: "실패는 성공의 일부다", author: "", category: "인생어록" },
  { text: "멈추지 마라, 계속 나아가라", author: "", category: "인생어록" },
  { text: "당신이 변하면 세상도 변한다", author: "", category: "인생어록" },
  { text: "작은 행복을 모으면 큰 행복이 된다", author: "", category: "인생어록" },
  { text: "슬픔도 지나간다", author: "", category: "인생어록" },
  { text: "희망을 잃지 마라", author: "", category: "인생어록" },
  { text: "당신의 이야기가 누군가를 구한다", author: "", category: "인생어록" },
  { text: "좋은 사람과 함께 하라", author: "", category: "인생어록" },
  { text: "오늘이 마지막이라면 어떻게 살겠는가", author: "", category: "인생어록" },
  { text: "미움보다 사랑을 택하라", author: "", category: "인생어록" },
  { text: "모든 것이 결국 잘될 것이다", author: "", category: "인생어록" },
  { text: "아프면 쉬어도 된다", author: "", category: "인생어록" },
  { text: "내 속도로 가면 된다", author: "", category: "인생어록" },
  { text: "완벽함을 추구하지 말고 노력하라", author: "", category: "인생어록" },
  { text: "한 발씩 나아가면 결국 도착한다", author: "", category: "인생어록" },
  { text: "남과 비교하지 말고 어제의 나와 비교하라", author: "", category: "인생어록" },
  { text: "당신은 혼자가 아니다", author: "", category: "인생어록" },
  { text: "꿈을 꾸면 현실이 된다", author: "", category: "인생어록" },
  { text: "용기는 두려움을 이긴다", author: "", category: "인생어록" },
  { text: "인생은 아름다운 모험이다", author: "", category: "인생어록" },
  { text: "현재를 즐겨라", author: "", category: "인생어록" },
  { text: "당신의 노력은 결코 헛되지 않다", author: "", category: "인생어록" },
  { text: "감정도 파도처럼 밀고 빠진다", author: "", category: "인생어록" },
  { text: "힘들 때일수록 웃으려 노력하라", author: "", category: "인생어록" },
  { text: "지금이 가장 소중한 순간이다", author: "", category: "인생어록" },
  { text: "당신의 선택이 당신을 정의한다", author: "", category: "인생어록" },
  { text: "모든 것이 다 되지 않아도 괜찮다", author: "", category: "인생어록" },
  { text: "살아있다는 것 자체가 축복이다", author: "", category: "인생어록" },
  { text: "좋은 추억이 최고의 재산이다", author: "", category: "인생어록" },
  { text: "후회보다 도전을 하라", author: "", category: "인생어록" },
  { text: "버팀목은 항상 곁에 있다", author: "", category: "인생어록" },
  { text: "나약해도 괜찮다", author: "", category: "인생어록" },
  { text: "새로운 날이 또 온다", author: "", category: "인생어록" },
  { text: "상황은 변하지만 당신은 강하다", author: "", category: "인생어록" },
  { text: "모든 계절이 아름답다", author: "", category: "인생어록" },
  { text: "답은 안에 있다", author: "", category: "인생어록" },
  { text: "현재에 충실하면 미래도 좋아진다", author: "", category: "인생어록" },
  { text: "처음부터 잘할 수는 없다", author: "", category: "인생어록" },
  { text: "나를 사랑하는 것부터 시작하라", author: "", category: "인생어록" },
  { text: "시간이 모든 것을 해결하지는 않지만 낫게 만든다", author: "", category: "인생어록" },
  { text: "언제든 시작할 수 있다", author: "", category: "인생어록" },
  { text: "당신의 노력을 믿어라", author: "", category: "인생어록" },
  { text: "문제 있는 사람이 있는 것 아니라 상황이 있을 뿐이다", author: "", category: "인생어록" },
  { text: "스스로를 응원해주라", author: "", category: "인생어록" },
  { text: "어둠 속에도 빛이 있다", author: "", category: "인생어록" },
  { text: "당신이 누군가의 빛이 될 수 있다", author: "", category: "인생어록" },
  { text: "괜찮지 않아도 괜찮다고 말해도 된다", author: "", category: "인생어록" },
  { text: "혼자가 아니라는 걸 기억해", author: "", category: "인생어록" },
  { text: "우리는 함께 강하다", author: "", category: "인생어록" },
  { text: "내일은 다른 날이다", author: "", category: "인생어록" },
  { text: "당신이 있어서 감사하다", author: "", category: "인생어록" },
  { text: "최고의 시간은 지금이다", author: "", category: "인생어록" },
  { text: "앞으로만 가면 된다", author: "", category: "인생어록" },
  { text: "당신은 그럴 자격이 있다", author: "", category: "인생어록" }
];

export default quotes;
